### ISSUE TITLE
AttributeError: undefined symbol: CDF_TT2000_to_UTC_parts

### ISSUE THREAD

**Issue by jester2** [spacepy/spacepy#142]
When opening a particular CDF file with a key that uses TT2000 data type, and with a timestamp issue that I'm not sure what is about, I am getting the following error:
```
Traceback (most recent call last):
  File "/home/lucasc/test_venv/lib/python3.6/site-packages/spacepy/pycdf/__init__.py", line 859, in tt2000_to_datetime
    self._library.CDF_TT2000_to_UTC_parts(
  File "/opt/python/3.6.5.3/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/opt/python/3.6.5.3/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /home/lucasc/test_venv/cdf37_1-install/lib/libcdf.so: undefined symbol: CDF_TT2000_to_UTC_parts

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lucasc/test_venv/lib/python3.6/site-packages/spacepy/pycdf/__init__.py", line 850, in tt2000_to_datetime
    yyyy = ctypes.c_double(0)
SystemError: <class 'ctypes.c_double'> returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lucasc/cdf_to_sqlite/convert.py", line 51, in getChannelData
    chanStack = cdfFile[chan][stack][0:lastValidRecord]
  File "/home/lucasc/test_venv/lib/python3.6/site-packages/spacepy/pycdf/__init__.py", line 2490, in __getitem__
    return hslice.convert_input_array(result)
  File "/home/lucasc/test_venv/lib/python3.6/site-packages/spacepy/pycdf/__init__.py", line 3322, in convert_input_array
    result = lib.v_tt2000_to_datetime(result)
  File "/home/lucasc/test_venv/lib/python3.6/site-packages/spacepy/pycdf/__init__.py", line 850, in tt2000_to_datetime
    yyyy = ctypes.c_double(0)
SystemError: <class 'ctypes.c_double'> returned a result with an error set
```

### OS, Python version, and dependency version information:
```
python 3.6.5.3 running on gcc 7.3.0
nasa cdf library 3.7.1
spacepy 0.1.6

numpy=1.15.4
scipy=1.2.1
matplotlib=3.0.3
```

**Comment by jtniehof** [comment]
Wowza. There are 6 test failures with cdf 3.7.1. Although I see they finally made the "invalid" day 9999/12/31 instead of 9999/12/13. I'll work on this.

**Comment by jtniehof** [comment]
If you're comfortable building from a PR you can also try that.

**Comment by jester2** [comment]
Just compiled using your pull request and that looks like it did the trick.  Thank you for the quick followup!
