### ISSUE TITLE
pip install fails on Mac and Linux

### ISSUE THREAD

**Issue by michaelaye** [spacepy/spacepy#150]
My issue is ...

### Minimal example to reproduce issue:

```
conda activate py37
pip install spacepy --user
```
### Error message/Traceback:

```
[...]
Building wheels for collected packages: spacepy, ffnet
  Building wheel for spacepy (setup.py) ... error
  ERROR: Complete output from command /Users/klay6683/miniconda3/envs/py37/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/tt/k11390b92vl_dygt4m0s7gjr008bbb/T/pip-install-i46lmq4e/spacepy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/tt/k11390b92vl_dygt4m0s7gjr008bbb/T/pip-wheel-6a08ide4 --python-tag cp37:
  ERROR: running bdist_wheel
  running build
  C compiler: gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/klay6683/miniconda3/envs/py37/include -arch x86_64 -I/Users/klay6683/miniconda3/envs/py37/include -arch x86_64

  creating build
  creating build/temp.macosx-10.9-x86_64-3.7
  creating build/temp.macosx-10.9-x86_64-3.7/spacepy
  creating build/temp.macosx-10.9-x86_64-3.7/spacepy/libspacepy
  compile options: '-c'
  gcc: spacepy/libspacepy/toolbox.c
  gcc: spacepy/libspacepy/randomkit.cgcc: spacepy/libspacepy/cn_solver.c

  gcc: spacepy/libspacepy/ctrace2d.c
  gcc: spacepy/libspacepy/poppy.c
  creating build/lib
  creating build/lib/spacepy
  gcc -bundle -undefined dynamic_lookup -L/Users/klay6683/miniconda3/envs/py37/lib -arch x86_64 -L/Users/klay6683/miniconda3/envs/py37/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.9-x86_64-3.7/spacepy/libspacepy/toolbox.o build/temp.macosx-10.9-x86_64-3.7/spacepy/libspacepy/randomkit.o build/temp.macosx-10.9-x86_64-3.7/spacepy/libspacepy/cn_solver.o build/temp.macosx-10.9-x86_64-3.7/spacepy/libspacepy/ctrace2d.o build/temp.macosx-10.9-x86_64-3.7/spacepy/libspacepy/poppy.o -lm -o build/lib/spacepy/libspacepy.so
  running config_fc
  unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
  customize Gnu95FCompiler
  Found executable /usr/local/bin/gfortran
  Found executable /usr/bin/ar
  Found executable /usr/bin/ranlib
  Reading fortran codes...
  	Reading file 'source/onera_desp_lib.f' (format:fix,strict)
  Line #26 in source/onera_desp_lib.f:"      REAL*4 FUNCTION IRBEM_FORTRAN_VERSION(argc, argv)   ! Called by ID"
  	analyzeline: No name/args pattern found for line.
  	Reading file 'source/wrappers.inc' (format:fix)
  	Reading file 'source/fortran_version.inc' (format:fix)
  Line #48 in source/onera_desp_lib.f:"      REAL*4 FUNCTION IRBEM_FORTRAN_RELEASE(argc, argv)   ! Called by ID"
  	analyzeline: No name/args pattern found for line.
  	Reading file 'source/wrappers.inc' (format:fix)
  	Reading file 'source/fortran_release.inc' (format:fix)
  Line #70 in source/onera_desp_lib.f:"      REAL*4 FUNCTION GET_IRBEM_NTIME_MAX(argc, argv)   ! Called by IDL"
  	analyzeline: No name/args pattern found for line.
  	Reading file 'source/wrappers.inc' (format:fix)
  	Reading file 'source/ntime_max.inc' (format:fix)
  Line #89 in source/onera_desp_lib.f:"      REAL*4 FUNCTION make_lstar(argc, argv)   ! Called by IDL"
  	analyzeline: No name/args pattern found for line.
  	Reading file 'source/wrappers.inc' (format:fix)
  	Reading file 'source/variables.inc' (format:fix)
  	Reading file 'source/ntime_max.inc' (format:fix)
  Line #228 in source/onera_desp_lib.f:"      REAL*4 FUNCTION make_lstar_shell_splitting(argc, argv)   ! Called "
  	analyzeline: No name/args pattern found for line.
  	Reading file 'source/wrappers.inc' (format:fix)
  	Reading file 'source/variables.inc' (format:fix)
  	Reading file 'source/ntime_max.inc' (format:fix)
  Line #370 in source/onera_desp_lib.f:"      REAL*4 FUNCTION Lstar_Phi(argc, argv)   ! Called by IDL"
  	analyzeline: No name/args pattern found for line.
  	Reading file 'source/wrappers.inc' (format:fix)
  	Reading file 'source/variables.inc' (format:fix)
  	Reading file 'source/ntime_max.inc' (format:fix)
  Line #442 in source/onera_desp_lib.f:"      REAL*4 FUNCTION drift_shell(argc, argv)   ! Called by IDL"
  	analyzeline: No name/args pattern found for line.
  	Reading file 'source/wrappers.inc' (format:fix)
  	Reading file 'source/variables.inc' (format:fix)
  Line #528 in source/onera_desp_lib.f:"      REAL*4 FUNCTION trace_field_line(argc, argv)   ! Called by IDL"
  	analyzeline: No name/args pattern found for line.
  	Reading file 'source/wrappers.inc' (format:fix)
  Line #552 in source/onera_desp_lib.f:"      REAL*4 FUNCTION trace_field_line2(argc, argv)   ! Called by IDL"
  	analyzeline: No name/args pattern found for line.
  	Reading file 'source/wrappers.inc' (format:fix)
  	Reading file 'source/variables.inc' (format:fix)
  Line #660 in source/onera_desp_lib.f:"      REAL*4 FUNCTION trace_field_line_towards_earth(argc, argv)   ! Cal"
  	analyzeline: No name/args pattern found for line.
  	Reading file 'source/wrappers.inc' (format:fix)
  	Reading file 'source/variables.inc' (format:fix)
  Line #747 in source/onera_desp_lib.f:"      REAL*4 FUNCTION find_mirror_point(argc, argv)   ! Called by IDL"
  	analyzeline: No name/args pattern found for line.
  	Reading file 'source/wrappers.inc' (format:fix)
  	Reading file 'source/variables.inc' (format:fix)
```
and a lot more like this. Do you maybe require g77 vs gfortran? I'm not sure, it's been a while I dabbled with FORTRAN.

### OS, Python version, and dependency version information:

```python
Darwin-18.2.0-x86_64-i386-64bit
sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
numpy=1.16.4
scipy=1.3.0
matplotlib=3.1.0
```

GFORTRAN via Homebrew:
```bash
$ gfortran --version                                                                                             (py37)
GNU Fortran (Homebrew GCC 9.1.0) 9.1.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by michaelaye** [comment]
Same happens on 3.6. Now trying GH version.

**Comment by michaelaye** [comment]
Same problem on Linux with the pip install:

```bash
Building wheels for collected packages: spacepy, ffnet
  Building wheel for spacepy (setup.py) ... error
  ERROR: Complete output from command /u/paige/maye/miniconda3/envs/py37/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-4rju_fas/spacepy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-5h54l07p --python-tag cp37:
  ERROR: running bdist_wheel
  running build
  C compiler: gcc -pthread -B /u/paige/maye/miniconda3/envs/py37/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC

  creating build
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/spacepy
  creating build/temp.linux-x86_64-3.7/spacepy/libspacepy
  compile options: '-c'
  gcc: spacepy/libspacepy/poppy.c
  gcc: spacepy/libspacepy/randomkit.c
  gcc: spacepy/libspacepy/ctrace2d.cgcc: spacepy/libspacepy/toolbox.c

  gcc: spacepy/libspacepy/cn_solver.c
  creating build/lib
  creating build/lib/spacepy
  gcc -pthread -shared -B /u/paige/maye/miniconda3/envs/py37/compiler_compat -L/u/paige/maye/miniconda3/envs/py37/lib -Wl,-rpath=/u/paige/maye/miniconda3/envs/py37/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/spacepy/libspacepy/randomkit.o build/temp.linux-x86_64-3.7/spacepy/libspacepy/toolbox.o build/temp.linux-x86_64-3.7/spacepy/libspacepy/ctrace2d.o build/temp.linux-x86_64-3.7/spacepy/libspacepy/poppy.o build/temp.linux-x86_64-3.7/spacepy/libspacepy/cn_solver.o -lm -o build/lib/spacepy/libspacepy.so
  running config_fc
  unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
  customize Gnu95FCompiler
  Found executable /usr/bin/gfortran
  Found executable /usr/bin/ar
  Found executable /usr/bin/ranlib
  Reading fortran codes...
  	Reading file 'source/onera_desp_lib.f' (format:fix,strict)
  Line #26 in source/onera_desp_lib.f:"      REAL*4 FUNCTION IRBEM_FORTRAN_VERSION(argc, argv)   ! Called by ID"
  	analyzeline: No name/args pattern found for line.
  	Reading file 'source/wrappers.inc' (format:fix)
  	Reading file 'source/fortran_version.inc' (format:fix)
  Line #48 in source/onera_desp_lib.f:"      REAL*4 FUNCTION IRBEM_FORTRAN_RELEASE(argc, argv)   ! Called by ID"
  	analyzeline: No name/args pattern found for line.
  	Reading file 'source/wrappers.inc' (format:fix)
  	Reading file 'source/fortran_release.inc' (format:fix)
  Line #70 in source/onera_desp_lib.f:"      REAL*4 FUNCTION GET_IRBEM_NTIME_MAX(argc, argv)   ! Called by IDL"
  	analyzeline: No name/args pattern found for line.
  	Reading file 'source/wrappers.inc' (format:fix)
  	Reading file 'source/ntime_max.inc' (format:fix)
  Line #89 in source/onera_desp_lib.f:"      REAL*4 FUNCTION make_lstar(argc, argv)   ! Called by IDL"
  	analyzeline: No name/args pattern found for line.
  	Reading file 'source/wrappers.inc' (format:fix)
  	Reading file 'source/variables.inc' (format:fix)
  	Reading file 'source/ntime_max.inc' (format:fix)
  Line #228 in source/onera_desp_lib.f:"      REAL*4 FUNCTION make_lstar_shell_splitting(argc, argv)   ! Called "
  	analyzeline: No name/args pattern found for line.
  	Reading file 'source/wrappers.inc' (format:fix)
  	Reading file 'source/variables.inc' (format:fix)
  	Reading file 'source/ntime_max.inc' (format:fix)
  Line #370 in source/onera_desp_lib.f:"      REAL*4 FUNCTION Lstar_Phi(argc, argv)   ! Called by IDL"
  	analyzeline: No name/args pattern found for line.
  	Reading file 'source/wrappers.inc' (format:fix)
  	Reading file 'source/variables.inc' (format:fix)
  	Reading file 'source/ntime_max.inc' (format:fix)
```

**Comment by michaelaye** [comment]
I realized maybe that my error reporting is missing a few important points, so here's more:
The print-out also has a lot of these:

```
analyzeline: implied-DO list "((x(i,j),i=1,9),j=31,40)" is not supported. Skipping.
```
FORTRAN compiler issues? A quick browse leads me to an INTEL page about compiling old FORTRAN code?

Here's the last full traceback:

```bash
 Traceback (most recent call last):
    File "/u/paige/maye/miniconda3/envs/py37/bin/f2py", line 12, in <module>
      sys.exit(main())
    File "/u/paige/maye/miniconda3/envs/py37/lib/python3.7/site-packages/numpy/f2py/f2py2e.py", line 685, in main
      run_main(sys.argv[1:])
    File "/u/paige/maye/miniconda3/envs/py37/lib/python3.7/site-packages/numpy/f2py/f2py2e.py", line 425, in run_main
      postlist = callcrackfortran(files, options)
    File "/u/paige/maye/miniconda3/envs/py37/lib/python3.7/site-packages/numpy/f2py/f2py2e.py", line 329, in callcrackfortran
      postlist = crackfortran.crackfortran(files)
    File "/u/paige/maye/miniconda3/envs/py37/lib/python3.7/site-packages/numpy/f2py/crackfortran.py", line 3251, in crackfortran
      readfortrancode(files, crackline)
    File "/u/paige/maye/miniconda3/envs/py37/lib/python3.7/site-packages/numpy/f2py/crackfortran.py", line 501, in readfortrancode
      dowithline(finalline)
    File "/u/paige/maye/miniconda3/envs/py37/lib/python3.7/site-packages/numpy/f2py/crackfortran.py", line 796, in crackline
      analyzeline(m, pat[1], line)
    File "/u/paige/maye/miniconda3/envs/py37/lib/python3.7/site-packages/numpy/f2py/crackfortran.py", line 1184, in analyzeline
      for e in markoutercomma(ll).split('@,@'):
    File "/u/paige/maye/miniconda3/envs/py37/lib/python3.7/site-packages/numpy/f2py/crackfortran.py", line 833, in markoutercomma
      assert not f, repr((f, line, l))
  AssertionError: (-1, 'xminp_l = 1.0)   ! minimum lshell to calculate proto', 'xminp_l = 1.0)   ! minimum lshell to calculate proto')
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-4rju_fas/spacepy/setup.py", line 833, in <module>
      setup(**setup_kwargs)
    File "/u/paige/maye/miniconda3/envs/py37/lib/python3.7/site-packages/numpy/distutils/core.py", line 171, in setup
      return old_setup(**new_attr)
    File "/u/paige/maye/miniconda3/envs/py37/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/u/paige/maye/miniconda3/envs/py37/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/u/paige/maye/miniconda3/envs/py37/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/u/paige/maye/miniconda3/envs/py37/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/u/paige/maye/miniconda3/envs/py37/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/u/paige/maye/miniconda3/envs/py37/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/u/paige/maye/miniconda3/envs/py37/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-4rju_fas/spacepy/setup.py", line 641, in run
      self.compile_irbempy()
    File "/tmp/pip-install-4rju_fas/spacepy/setup.py", line 413, in compile_irbempy
      subprocess.check_call(cmd)
    File "/u/paige/maye/miniconda3/envs/py37/lib/python3.7/subprocess.py", line 347, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['f2py', '--overwrite-signature', '-m', 'irbempylib', '-h', 'irbempylib.pyf', 'source/onera_desp_lib.f', 'source/CoordTrans.f', 'source/AE8_AP8.f', 'source/find_foot.f', 'source/drift_bounce_orbit.f', 'only:', 'make_lstar1', 'make_lstar_shell_splitting1', 'find_foot_point1', 'coord_trans1', 'find_magequator1', 'find_mirror_point1', 'get_field1', 'get_ae8_ap8_flux', 'fly_in_nasa_aeap1', 'trace_field_line2_1', 'trace_field_line_towards_earth1', 'trace_drift_bounce_orbit', ':']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for spacepy
```

**Comment by michaelaye** [comment]
The GH version compiled but with a lot of skipped items due to not supported things with gfortran, but also a lot of warnings for unused variables, undefined behavior, and potential data value changes from data-lossy type conversions? 

```fortran
Warning: Unused variable 'iyear' declared at (1) [-Wunused-variable]
source/onera_desp_lib.f:413:50:

  413 |       integer*4 int_field_select, ext_field_select
      |                                                  1
Warning: Unused variable 'ext_field_select' declared at (1) [-Wunused-variable]
source/onera_desp_lib.f:272:29:

  272 |       INTEGER*4    isat,iyear,IPA,kint,ifail
      |                             1
Warning: Unused variable 'iyear' declared at (1) [-Wunused-variable]
source/onera_desp_lib.f:129:29:

  129 |       INTEGER*4    isat,iyear,kint,ifail
      |                             1
Warning: Unused variable 'iyear' declared at (1) [-Wunused-variable]
source/onera_desp_lib.f:2958:0:

 2958 |           Dens(J,I)=D(J)
      |
Warning: iteration 8 invokes undefined behavior [-Waggressive-loop-optimizations]
source/onera_desp_lib.f:2957:0:
```
lots more like these and these:

```fortran
Warning: Possible change of value in conversion from INTEGER(8) to INTEGER(4) at (1) [-Wconversion]
source/onera_desp_lib.f:1165:11:

 1165 |        j = loc(argc)                    ! Obtains the number of arguments (argc)
      |           1
Warning: Possible change of value in conversion from INTEGER(8) to INTEGER(4) at (1) [-Wconversion]
source/onera_desp_lib.f:1741:11:

 1741 |        j = loc(argc)                    ! Obtains the number of arguments (argc)
      |           1
Warning: Possible change of value in conversion from INTEGER(8) to INTEGER(4) at (1) [-Wconversion]
source/onera_desp_lib.f:1764:11:

 1764 |        j = loc(argc)                    ! Obtains the number of arguments (argc)
      |           1
Warning: Possible change of value in conversion from INTEGER(8) to INTEGER(4) at (1) [-Wconversion]
source/onera_desp_lib.f:1788:11...
```
and lots more like those.

**Comment by drsteve** [comment]
Thanks for the report!

The last release on PyPI doesn't build with GCC>=8 (and has some incompatibilities with f2py in numpy>=1.16), as detailed in (closed) issues #108 and #134.

Building from the repository should work just fine for recent GCC and numpy, as these issues were addressed in PRs #106 and #139 
The warnings don't cause behavioral issues in anything we've looked at, and are owned by the IRBEM library (an upstream dependency). I'm working with the maintainers of that library to try to get their codebase modernized.

We're prepping for a new release so that installing from PyPI will work for up-to-date system configurations. In the mean time, if you have trouble with the repository version please let us know.
I'll close this tracker at the end of the day unless you have other concerns.

**Comment by michaelaye** [comment]
My last entry was for the repo version (I called it "GH version").

**Comment by michaelaye** [comment]
Just a question though: How can this have no impact:

```fortran
implied-DO list "(mappmax (i), i=11761,12250)" is not supported. Skipping.
```
and many more like these?

What does the compiler really do when it says "Skipping"? Is that calculation not done? That function call missing?

(This feedback is from the repository install).

**Comment by drsteve** [comment]
Understood.

We provide a _limited_ Python interface to the IRBEM library, through the irbempy module. We don't maintain IRBEM, but are working with the maintainers of IRBEM to try to get their code modernized. All of the warnings (no errors) are from the IRBEM compilation. As far as we are aware, the warnings do not affect the wrapped functionality.


Note on the `enKF_test.py` file:
All of our test suite is named `test_XXX.py`. This file is not part of the test suite and has not been maintained (and hence does not pass as it refers to obsolete code). We are aware of this and the file is slated for deletion, but this is pending some further dev discussion on the future of the module it relates to. `test_spacepy.py` and auto-discovery of tests is not recommended at this time.

**Comment by jtniehof** [comment]
test_spacepy should work since it isn't pulling in enKF_test (intentionally). Any other sort of test discovery beyond unittest.main() is likely to go horribly wrong.
