### ISSUE TITLE
spacepy 0.2.0 fails to install in RHSLC python 3.6

### ISSUE THREAD

**Issue by berniegsfc** [spacepy/spacepy#203]
spacepy 0.2.0 fails to install in RH's python 3.6..  Note that version 0.1.16 does install and function in the same python environment.

### Minimal example to reproduce issue:

```
gs672-tara $ . /usr/local/cdf37_1/bin/definitions.B
gs672-tara $ /opt/rh/rh-python36/root/bin/virtualenv ~/opt/python/3/test   
gs672-tara $ . ~/opt/python/3/test/bin/activate
(test) gs672-tara $ pip install --upgrade pip
(test) gs672-tara $ pip install spacepy
```

### Error message/Traceback:

```
gs672-tara $ . /usr/local/cdf37_1/bin/definitions.B
gs672-tara $ /opt/rh/rh-python36/root/bin/virtualenv ~/opt/python/3/test   
Using base prefix '/opt/rh/rh-python36/root/usr'
New python executable in /home/btharris/opt/python/3/test/bin/python3
Also creating executable in /home/btharris/opt/python/3/test/bin/python
Installing setuptools, pip, wheel...done.
gs672-tara $ . ~/opt/python/3/test/bin/activate
(test) gs672-tara $ pip install --upgrade pip
Cache entry deserialization failed, entry ignored
Collecting pip
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/30/db/9e38760b32e3e7f40cce46dd5fb107b8c73840df38f0046d8e6514e675a1/pip-19.2.3-py2.py3-none-any.whl (1.4MB)
    100% |################################| 1.4MB 1.3MB/s 
Installing collected packages: pip
  Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
      Successfully uninstalled pip-9.0.1
Successfully installed pip-19.2.3
(test) gs672-tara $ pip install spacepy
Collecting spacepy
  Using cached https://files.pythonhosted.org/packages/56/83/aa1bd25b7d03e3c5a062e94bf396c99149a91d0ff97e60484030f3093d89/spacepy-0.2.0.tar.gz
Collecting numpy>=1.6 (from spacepy)
  Downloading https://files.pythonhosted.org/packages/e5/e6/c3fdc53aed9fa19d6ff3abf97dfad768ae3afce1b7431f7500000816bda5/numpy-1.17.2-cp36-cp36m-manylinux1_x86_64.whl (20.4MB)
     |################################| 20.4MB 8.8MB/s 
Collecting scipy>=0.10 (from spacepy)
  Downloading https://files.pythonhosted.org/packages/29/50/a552a5aff252ae915f522e44642bb49a7b7b31677f9580cfd11bcc869976/scipy-1.3.1-cp36-cp36m-manylinux1_x86_64.whl (25.2MB)
     |################################| 25.2MB 24.0MB/s 
Collecting matplotlib>=1.5 (from spacepy)
  Using cached https://files.pythonhosted.org/packages/57/4f/dd381ecf6c6ab9bcdaa8ea912e866dedc6e696756156d8ecc087e20817e2/matplotlib-3.1.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting h5py (from spacepy)
  Downloading https://files.pythonhosted.org/packages/60/06/cafdd44889200e5438b897388f3075b52a8ef01f28a17366d91de0fa2d05/h5py-2.10.0-cp36-cp36m-manylinux1_x86_64.whl (2.9MB)
     |################################| 2.9MB 21.1MB/s 
Collecting ffnet; platform_system != "Windows" (from spacepy)
Collecting networkx (from spacepy)
Collecting python_dateutil (from spacepy)
  Using cached https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl
Collecting cycler>=0.10 (from matplotlib>=1.5->spacepy)
  Using cached https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
Collecting kiwisolver>=1.0.1 (from matplotlib>=1.5->spacepy)
  Using cached https://files.pythonhosted.org/packages/f8/a1/5742b56282449b1c0968197f63eae486eca2c35dcd334bab75ad524e0de1/kiwisolver-1.1.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 (from matplotlib>=1.5->spacepy)
  Using cached https://files.pythonhosted.org/packages/11/fa/0160cd525c62d7abd076a070ff02b2b94de589f1a9789774f17d7c54058e/pyparsing-2.4.2-py2.py3-none-any.whl
Collecting six (from h5py->spacepy)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting decorator>=4.3.0 (from networkx->spacepy)
  Using cached https://files.pythonhosted.org/packages/5f/88/0075e461560a1e750a0dcbf77f1d9de775028c37a19a346a6c565a257399/decorator-4.4.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools in /home/btharris/opt/python/3/test/lib/python3.6/site-packages (from kiwisolver>=1.0.1->matplotlib>=1.5->spacepy) (28.8.0)
Building wheels for collected packages: spacepy
  Building wheel for spacepy (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/btharris/opt/python/3/test/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ay4h9n2f/spacepy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ay4h9n2f/spacepy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-szgma6z5 --python-tag cp36
       cwd: /tmp/pip-install-ay4h9n2f/spacepy/
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-ay4h9n2f/spacepy/setup.py", line 36, in <module>
      from numpy.distutils.core import setup
  ModuleNotFoundError: No module named 'numpy'
  ----------------------------------------
  ERROR: Failed building wheel for spacepy
  Running setup.py clean for spacepy
  ERROR: Command errored out with exit status 1:
   command: /home/btharris/opt/python/3/test/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ay4h9n2f/spacepy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ay4h9n2f/spacepy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: /tmp/pip-install-ay4h9n2f/spacepy
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-ay4h9n2f/spacepy/setup.py", line 36, in <module>
      from numpy.distutils.core import setup
  ModuleNotFoundError: No module named 'numpy'
  ----------------------------------------
  ERROR: Failed cleaning build dir for spacepy
Failed to build spacepy
Installing collected packages: numpy, scipy, six, cycler, python-dateutil, kiwisolver, pyparsing, matplotlib, h5py, ffnet, decorator, networkx, spacepy
  Running setup.py install for spacepy ... error
    ERROR: Command errored out with exit status 1:
     command: /home/btharris/opt/python/3/test/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ay4h9n2f/spacepy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ay4h9n2f/spacepy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-eccbd30e/install-record.txt --single-version-externally-managed --compile --install-headers /home/btharris/opt/python/3/test/include/site/python3.6/spacepy
         cwd: /tmp/pip-install-ay4h9n2f/spacepy/
    Complete output (199 lines):
    running install
    running build
    C compiler: gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -I/opt/rh/rh-python36/root/usr/include -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC
    
    creating build
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/spacepy
    creating build/temp.linux-x86_64-3.6/spacepy/libspacepy
    compile options: '-c'
    gcc: spacepy/libspacepy/randomkit.c
    gcc: spacepy/libspacepy/poppy.c
    gcc: spacepy/libspacepy/toolbox.c
    gcc: spacepy/libspacepy/ctrace2d.c
    gcc: spacepy/libspacepy/cn_solver.c
    creating build/lib
    creating build/lib/spacepy
    gcc -pthread -shared -L/opt/rh/rh-python36/root/usr/lib64-Wl,-z,relro -Wl,-rpath,/opt/rh/rh-python36/root/usr/lib64 -Wl,--enable-new-dtags build/temp.linux-x86_64-3.6/spacepy/libspacepy/randomkit.o build/temp.linux-x86_64-3.6/spacepy/libspacepy/poppy.o build/temp.linux-x86_64-3.6/spacepy/libspacepy/cn_solver.o build/temp.linux-x86_64-3.6/spacepy/libspacepy/toolbox.o build/temp.linux-x86_64-3.6/spacepy/libspacepy/ctrace2d.o -lm -o build/lib/spacepy/libspacepy.so
    running config_fc
    unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
    running config_cc
    unifing config_cc, config, build_clib, build_ext, build commands --compiler options
    running build_py
    copying spacepy/rst.py -> build/lib/spacepy
    copying spacepy/__init__.py -> build/lib/spacepy
    copying spacepy/LANLstar.py -> build/lib/spacepy
    copying spacepy/datamanager.py -> build/lib/spacepy
    copying spacepy/data_assimilation.py -> build/lib/spacepy
    copying spacepy/poppy.py -> build/lib/spacepy
    copying spacepy/omni.py -> build/lib/spacepy
    copying spacepy/time.py -> build/lib/spacepy
    copying spacepy/empiricals.py -> build/lib/spacepy
    copying spacepy/ae9ap9.py -> build/lib/spacepy
    copying spacepy/radbelt.py -> build/lib/spacepy
    copying spacepy/coordinates.py -> build/lib/spacepy
    copying spacepy/spacepy_EnKF.py -> build/lib/spacepy
    copying spacepy/seapy.py -> build/lib/spacepy
    copying spacepy/datamodel.py -> build/lib/spacepy
    copying spacepy/lib.py -> build/lib/spacepy
    creating build/lib/spacepy/irbempy
    copying spacepy/irbempy/irbempy.py -> build/lib/spacepy/irbempy
    copying spacepy/irbempy/__init__.py -> build/lib/spacepy/irbempy
    creating build/lib/spacepy/pycdf
    copying spacepy/pycdf/__init__.py -> build/lib/spacepy/pycdf
    copying spacepy/pycdf/const.py -> build/lib/spacepy/pycdf
    creating build/lib/spacepy/plot
    copying spacepy/plot/utils.py -> build/lib/spacepy/plot
    copying spacepy/plot/__init__.py -> build/lib/spacepy/plot
    copying spacepy/plot/carrington.py -> build/lib/spacepy/plot
    copying spacepy/plot/apionly.py -> build/lib/spacepy/plot
    copying spacepy/plot/colourmaps.py -> build/lib/spacepy/plot
    copying spacepy/plot/spectrogram.py -> build/lib/spacepy/plot
    creating build/lib/spacepy/pybats
    copying spacepy/pybats/pwom.py -> build/lib/spacepy/pybats
    copying spacepy/pybats/interact.py -> build/lib/spacepy/pybats
    copying spacepy/pybats/__init__.py -> build/lib/spacepy/pybats
    copying spacepy/pybats/dgcpm.py -> build/lib/spacepy/pybats
    copying spacepy/pybats/ram.py -> build/lib/spacepy/pybats
    copying spacepy/pybats/kyoto.py -> build/lib/spacepy/pybats
    copying spacepy/pybats/rim.py -> build/lib/spacepy/pybats
    copying spacepy/pybats/gitm.py -> build/lib/spacepy/pybats
    copying spacepy/pybats/bats.py -> build/lib/spacepy/pybats
    copying spacepy/pybats/dipole.py -> build/lib/spacepy/pybats
    copying spacepy/pybats/trace2d.py -> build/lib/spacepy/pybats
    copying spacepy/pybats/batsmath.py -> build/lib/spacepy/pybats
    copying spacepy/pybats/qotree.py -> build/lib/spacepy/pybats
    creating build/lib/spacepy/toolbox
    copying spacepy/toolbox/__init__.py -> build/lib/spacepy/toolbox
    creating build/lib/spacepy/data
    copying spacepy/data/spacepy_altgrid.mplstyle -> build/lib/spacepy/data
    copying spacepy/data/spacepy_polar.mplstyle -> build/lib/spacepy/data
    copying spacepy/data/tai-utc.dat -> build/lib/spacepy/data
    copying spacepy/data/SEA_epochs_OMNI.txt -> build/lib/spacepy/data
    copying spacepy/data/spacepy.mplstyle -> build/lib/spacepy/data
    creating build/lib/spacepy/data/LANLstar
    copying spacepy/data/LANLstar/Lmax_T01STORM.net.gz -> build/lib/spacepy/data/LANLstar
    copying spacepy/data/LANLstar/LANLstar_T01QUIET.net.gz -> build/lib/spacepy/data/LANLstar
    copying spacepy/data/LANLstar/LANLstar_T05.net.gz -> build/lib/spacepy/data/LANLstar
    copying spacepy/data/LANLstar/LANLstar_T01STORM.net.gz -> build/lib/spacepy/data/LANLstar
    copying spacepy/data/LANLstar/Lmax_T96.net.gz -> build/lib/spacepy/data/LANLstar
    copying spacepy/data/LANLstar/LANLstar_T96.net.gz -> build/lib/spacepy/data/LANLstar
    copying spacepy/data/LANLstar/LANLstar_OPQuiet.net.gz -> build/lib/spacepy/data/LANLstar
    copying spacepy/data/LANLstar/LANLstar_T89.net.gz -> build/lib/spacepy/data/LANLstar
    copying spacepy/data/LANLstar/LANLstar_RAMSCB.net.gz -> build/lib/spacepy/data/LANLstar
    copying spacepy/data/LANLstar/Lmax_T05.net.gz -> build/lib/spacepy/data/LANLstar
    copying spacepy/data/LANLstar/Lmax_OPDyn.net.gz -> build/lib/spacepy/data/LANLstar
    copying spacepy/data/LANLstar/Lmax_T89.net.gz -> build/lib/spacepy/data/LANLstar
    copying spacepy/data/LANLstar/Lmax_OPQuiet.net.gz -> build/lib/spacepy/data/LANLstar
    copying spacepy/data/LANLstar/LANLstar_OPDyn.net.gz -> build/lib/spacepy/data/LANLstar
    copying spacepy/data/LANLstar/Lmax_T01QUIET.net.gz -> build/lib/spacepy/data/LANLstar
    creating build/lib/spacepy/data/TS07D
    creating build/lib/spacepy/data/TS07D/TAIL_PAR
    copying spacepy/data/TS07D/TAIL_PAR/tailamhr_e_23.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
    copying spacepy/data/TS07D/TAIL_PAR/tailamhr_o_44.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
    copying spacepy/data/TS07D/TAIL_PAR/tailamhr_e_53.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
    copying spacepy/data/TS07D/TAIL_PAR/tailamhr_e_52.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
    copying spacepy/data/TS07D/TAIL_PAR/tailamebhr4.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
    copying spacepy/data/TS07D/TAIL_PAR/tailamhr_e_21.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
    copying spacepy/data/TS07D/TAIL_PAR/tailamhr_e_54.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
    copying spacepy/data/TS07D/TAIL_PAR/tailamhr_e_11.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
    copying spacepy/data/TS07D/TAIL_PAR/tailamhr_o_42.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
    copying spacepy/data/TS07D/TAIL_PAR/tailamhr_o_54.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
    copying spacepy/data/TS07D/TAIL_PAR/tailamhr_e_43.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
    copying spacepy/data/TS07D/TAIL_PAR/tailamebhr5.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
    copying spacepy/data/TS07D/TAIL_PAR/tailamebhr2.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
    copying spacepy/data/TS07D/TAIL_PAR/tailamhr_e_32.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
    copying spacepy/data/TS07D/TAIL_PAR/tailamhr_e_31.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
    copying spacepy/data/TS07D/TAIL_PAR/tailamhr_o_34.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
    copying spacepy/data/TS07D/TAIL_PAR/tailamhr_e_44.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
    copying spacepy/data/TS07D/TAIL_PAR/tailamhr_o_24.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
    copying spacepy/data/TS07D/TAIL_PAR/tailamhr_o_51.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
    copying spacepy/data/TS07D/TAIL_PAR/tailamhr_e_24.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
    copying spacepy/data/TS07D/TAIL_PAR/tailamhr_e_41.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
    copying spacepy/data/TS07D/TAIL_PAR/tailamhr_e_51.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
    copying spacepy/data/TS07D/TAIL_PAR/tailamebhr3.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
    copying spacepy/data/TS07D/TAIL_PAR/tailamhr_o_31.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
    copying spacepy/data/TS07D/TAIL_PAR/tailamhr_e_14.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
    copying spacepy/data/TS07D/TAIL_PAR/tailamhr_o_12.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
    copying spacepy/data/TS07D/TAIL_PAR/tailamhr_o_21.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
    copying spacepy/data/TS07D/TAIL_PAR/tailamhr_o_32.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
    copying spacepy/data/TS07D/TAIL_PAR/tailamhr_o_33.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
    copying spacepy/data/TS07D/TAIL_PAR/tailamhr_e_13.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
    copying spacepy/data/TS07D/TAIL_PAR/tailamhr_o_22.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
    copying spacepy/data/TS07D/TAIL_PAR/tailamhr_o_23.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
    copying spacepy/data/TS07D/TAIL_PAR/tailamhr_o_14.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
    copying spacepy/data/TS07D/TAIL_PAR/tailamhr_e_22.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
    copying spacepy/data/TS07D/TAIL_PAR/tailamhr_e_33.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
    copying spacepy/data/TS07D/TAIL_PAR/tailamhr_e_42.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
    copying spacepy/data/TS07D/TAIL_PAR/tailamhr_o_41.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
    copying spacepy/data/TS07D/TAIL_PAR/tailamhr_o_53.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
    copying spacepy/data/TS07D/TAIL_PAR/tailamhr_o_11.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
    copying spacepy/data/TS07D/TAIL_PAR/tailamhr_e_34.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
    copying spacepy/data/TS07D/TAIL_PAR/tailamhr_e_12.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
    copying spacepy/data/TS07D/TAIL_PAR/tailamhr_o_52.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
    copying spacepy/data/TS07D/TAIL_PAR/tailamebhr1.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
    copying spacepy/data/TS07D/TAIL_PAR/tailamhr_o_43.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
    copying spacepy/data/TS07D/TAIL_PAR/tailamhr_o_13.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
    customize Gnu95FCompiler
    Found executable /usr/bin/gfortran
    Found executable /usr/bin/ar
    Found executable /usr/bin/ranlib
    Reading fortran codes...
    	Reading file 'source/onera_desp_lib.f' (format:fix,strict)
    	Reading file 'source/wrappers.inc' (format:fix)
    	Reading file 'source/fortran_version.inc' (format:fix)
    	Reading file 'source/wrappers.inc' (format:fix)
    	Reading file 'source/fortran_release.inc' (format:fix)
    	Reading file 'source/wrappers.inc' (format:fix)
    	Reading file 'source/ntime_max.inc' (format:fix)
    	Reading file 'source/wrappers.inc' (format:fix)
    	Reading file 'source/variables.inc' (format:fix)
    	Reading file 'source/ntime_max.inc' (format:fix)
    	Reading file 'source/wrappers.inc' (format:fix)
    Traceback (most recent call last):
      File "/home/btharris/opt/python/3/test/bin/f2py3", line 10, in <module>
        sys.exit(main())
      File "/home/btharris/opt/python/3/test/lib/python3.6/site-packages/numpy/f2py/f2py2e.py", line 685, in main
        run_main(sys.argv[1:])
      File "/home/btharris/opt/python/3/test/lib/python3.6/site-packages/numpy/f2py/f2py2e.py", line 425, in run_main
        postlist = callcrackfortran(files, options)
      File "/home/btharris/opt/python/3/test/lib/python3.6/site-packages/numpy/f2py/f2py2e.py", line 330, in callcrackfortran
        postlist = crackfortran.crackfortran(files)
      File "/home/btharris/opt/python/3/test/lib/python3.6/site-packages/numpy/f2py/crackfortran.py", line 3251, in crackfortran
        readfortrancode(files, crackline)
      File "/home/btharris/opt/python/3/test/lib/python3.6/site-packages/numpy/f2py/crackfortran.py", line 361, in readfortrancode
        l = fin.readline()
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/fileinput.py", line 299, in readline
        line = self._readline()
      File "/home/btharris/opt/python/3/test/lib64/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 2693: ordinal not in range(128)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ay4h9n2f/spacepy/setup.py", line 1001, in <module>
        setup(**setup_kwargs)
      File "/home/btharris/opt/python/3/test/lib/python3.6/site-packages/numpy/distutils/core.py", line 171, in setup
        return old_setup(**new_attr)
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/btharris/opt/python/3/test/lib/python3.6/site-packages/numpy/distutils/command/install.py", line 62, in run
        r = self.setuptools_run()
      File "/home/btharris/opt/python/3/test/lib/python3.6/site-packages/numpy/distutils/command/install.py", line 36, in setuptools_run
        return distutils_install.run(self)
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-ay4h9n2f/spacepy/setup.py", line 772, in run
        self.compile_irbempy()
      File "/tmp/pip-install-ay4h9n2f/spacepy/setup.py", line 524, in compile_irbempy
        subprocess.check_call(cmd)
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['f2py3', '--overwrite-signature', '-m', 'irbempylib', '-h', 'irbempylib.pyf', 'source/onera_desp_lib.f', 'source/CoordTrans.f', 'source/AE8_AP8.f', 'source/find_foot.f', 'source/drift_bounce_orbit.f', 'only:', 'make_lstar1', 'make_lstar_shell_splitting1', 'find_foot_point1', 'coord_trans1', 'find_magequator1', 'find_mirror_point1', 'get_field1', 'get_ae8_ap8_flux', 'fly_in_nasa_aeap1', 'trace_field_line2_1', 'trace_field_line_towards_earth1', 'trace_drift_bounce_orbit', ':']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/btharris/opt/python/3/test/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ay4h9n2f/spacepy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ay4h9n2f/spacepy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-eccbd30e/install-record.txt --single-version-externally-managed --compile --install-headers /home/btharris/opt/python/3/test/include/site/python3.6/spacepy Check the logs for full command output.
```

### OS, Python version, and dependency version information:

```
Linux-3.10.0-957.10.1.el7.x86_64-x86_64-with-redhat-7.6-Maipo
sys.version_info(major=3, minor=6, micro=3, releaselevel='final', serial=0)
numpy=1.17.2
scipy=1.3.1
matplotlib=3.1.1

gs672-tara $ rpm -qa | grep -i rh-python36
rh-python36-python-setuptools-36.5.0-1.el7.noarch
rh-python36-python-3.6.3-3.el7.x86_64
rh-python36-python-virtualenv-15.1.0-2.el7.noarch
rh-python36-python-pip-9.0.1-2.el7.noarch
rh-python36-runtime-2.0-1.el7.x86_64
rh-python36-2.0-1.el7.x86_64
rh-python36-python-libs-3.6.3-3.el7.x86_64
rh-python36-python-devel-3.6.3-3.el7.x86_64
rh-python36-python-tkinter-3.6.3-3.el7.x86_64

```

### Version of SpacePy
0.2.0 from pypi

**Comment by berniegsfc** [comment]
Installing numpy and then
pip install git+https://github.com/spacepy/spacepy
works (although I haven't actually exercised spacepy yet).

**Comment by asreimer** [comment]
I'm seeing the exact same `UnicodeDecode` problem that @berniegsfc observed. My OS is Ubuntu 18.04 with Python3.6. No issues in Python2.7 (as expected).

I can make spacepy install properly with:

    pip install git+https://github.com/spacepy/spacepy.git@736df223a067574f9f87c2697f61d17eb39898a3

which is installing directly from the commit that merged #193. But this has the nasty side effect of printing:

    This unreleased version of SpacePy is not supported by the SpacePy team.

every time one import spacepy (even though this installation method was recommended by the SpacepPy team!). I've noted this in a previous issue.

**Comment by jtniehof** [comment]
The fix for this should be included in 0.2.1, so a simple "pip install" should do the trick now. Please let me know one way or the other so we can close this.

**Comment by asreimer** [comment]
@jtniehof just tested. 0.2.1 installs perfectly with `pip install scipy==0.2.1`

Thank you for all the work you all have done on this!

**Comment by berniegsfc** [comment]
spacepy 0.2.1 now works for me to.  Thanks.

**Comment by jtniehof** [comment]
Thanks for checking! Closing.
