### ISSUE TITLE
SpacePy crashes with Docker 

### ISSUE THREAD

**Issue by xbonnin** [spacepy/spacepy#282]
We've just updated our SpacePy version to the 0.2.1 via pip.
I have now the following error when running a module of our data pipeline in a Docker container:

xbonnin@roc:/opt/roc/pipelines/rodp/RODP_PROD$ docker-compose run --rm pipeline python scripts/set_data_version.py --help
Starting rodp_prod_postgres_1 ... done
SpacePy: Space Science Tools for Python
  See __licence__ and __citation__ for licensing, and help() for HTML help.
Traceback (most recent call last):
  File "scripts/set_data_version.py", line 18, in <module>
    from spacepy.pycdf import CDF
  File "/usr/local/lib/python3.6/site-packages/spacepy/__init__.py", line 309, in <module>
    os.mkdir(DOT_FLN)
FileNotFoundError: [Errno 2] No such file or directory: '/home/xbonnin/.spacepy'

It seems the program crashes only because the .spacepy cannot be found (the Docker container - dedicated to the pipeline run only - indeed not contains any /home directory).

Is there a way to disable this feature in spacepy or do we have to create a specific /home/xbonnin directory each time we buidling the Docker container ? (Installation of the pipeline is already complex so if we could avoid this.)

For information, we use:

- SpacePy 0.2.1
-  Docker version 19.03.6, build 369ce74a3c
- docker-compose version 1.24.1, build 4667896b
- Docker image is built using python:3.6-jessie image

Thanks in advance,
Xavier Bonnin,  for the RPW/Solar Orbiter ground segment team

**Comment by balarsen** [comment]
@jtniehof, although an absolute requirement on the folder doesn't seem quite right, could spacepy just try and fail to not dealing with it?

**Comment by xbonnin** [comment]
I've added the commands:

RUN mkdir -p /home/${USER_NAME}/.spacepy
RUN chown -R ${USER_ID}:${GROUP_ID} /home/${USER_NAME}

to my Dockerfile, which seems to fix error.

But adding an extra command:

RUN touch /home/${USER_NAME}/.spacepy/spacepy.rc

Triggers this:

2020-02-29 17:13:43,326 - poppy.core.tools.exceptions - exceptions.py:108 - ERROR - Traceback (most recent call last):
  File "/usr/local/lib/python3.6/configparser.py", line 846, in items
    d.update(self._sections[section])
KeyError: 'spacepy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/poppy/core/pipeline.py", line 426, in _starter
    yield
  File "/usr/local/lib/python3.6/site-packages/poppy/core/pipeline.py", line 334, in _run_tasks
    self.check_and_run_task(task)
  File "/usr/local/lib/python3.6/site-packages/poppy/core/pipeline.py", line 372, in check_and_run_task
    task.run()
  File "/usr/local/lib/python3.6/site-packages/roc/film/tasks/l1_surv.py", line 114, in run
    from spacepy.pycdf import CDF
  File "/usr/local/lib/python3.6/site-packages/spacepy/__init__.py", line 318, in <module>
    _read_config(rcfile)
  File "/usr/local/lib/python3.6/site-packages/spacepy/__init__.py", line 277, in _read_config
    config = dict(cp.items('spacepy'))
  File "/usr/local/lib/python3.6/configparser.py", line 849, in items
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'spacepy'

**Comment by jtniehof** [comment]
Thanks. I'll look at setting up the config writer to be able to handle an empty existing file; that shouldn't be too hard and honestly makes sense (I can see somebody deleting everything in the files instead of just the file if they want the defaults back.)

@balarsen, I'm not sure about managing if the directory doesn't exist. It's probably possible but we do rely pretty heavily on DOTFLN existing throughout the code and the correct fallback isn't always obvious. Maybe we should open that as a future enhancement? I'm just always a little nervous about hiding problems the user might want/need to know about.

**Comment by xbonnin** [comment]
Ok for the moment I've just added the following lines to the Dockerfile:

RUN mkdir -p /home/${USER_NAME}/.spacepy
RUN chown -R ${USER_ID}:${GROUP_ID} /home/${USER_NAME}

I have still the spacepy welcome message each time I run the pipeline with the 'docker-compose run --rm' command, but at least no crash.

**Comment by xbonnin** [comment]
@jtniehof,

I have another error now (still with spacepy config file in a Docker container): 

```
2021-02-19 17:05:02,797 - poppy.core.tools.exceptions - exceptions.py:108 - ERROR - Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/poppy/pop/scripts/scripts.py", line 76, in load_plugins
    plugin.load()
  File "/usr/local/lib/python3.8/site-packages/poppy/core/plugin.py", line 225, in load
    self._check_module("commands")
  File "/usr/local/lib/python3.8/site-packages/poppy/core/plugin.py", line 58, in _check_module
    importlib.import_module(name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/site-packages/roc/film/commands.py", line 16, in <module>
    from roc.film.tasks.file_helpers import get_output_dir, get_products_dir, is_output_dir
  File "/usr/local/lib/python3.8/site-packages/roc/film/tasks/__init__.py", line 8, in <module>
    from roc.film.tasks.l1_sbm import *
  File "/usr/local/lib/python3.8/site-packages/roc/film/tasks/l1_sbm.py", line 8, in <module>
    from spacepy.pycdf import CDF
  File "/usr/local/lib/python3.8/site-packages/spacepy/__init__.py", line 385, in <module>
    os.mkdir(DOT_FLN)
FileExistsError: [Errno 17] File exists: '/pipeline/lib/spacepy/.spacepy'
```

Here is below the piece of code in the Dockerfile for initializing spacepy configuration env.:

```
ARG SPACEPY=/pipeline/lib/spacepy
ARG SPACEPY_DATA=/usr/local/lib/python3.8/site-packages/spacepy/data
RUN mkdir -p $SPACEPY && cp -r $SPACEPY_DATA $SPACEPY/. && chmod -R 2777 $SPACEPY
```

I assume the spacepy import crashes because /pipeline/lib/spacepy already exists with elements inside (os.mkdir does not like to create existing folder). Nevertheless, the import also crashes if the data/ folder is not found in /pipeline/lib/spacepy (and I cannot copy the data/ folder each time I run the Docker container, it needs to be copied when building the Docker image). 
N.B. I need to set the SPACEPY env. to a specific location with 2777 permission since several users need to run spacepy inside the Docker container (using /home/<user>/.spacepy location is hence not an option here).

**Comment by xbonnin** [comment]
Creating the .spacepy sub-folder in $SPACEPY (i.e., /pipeline/lib/spacepy) when building the docker image with the Dockerfile seems to fix the problem.

Commands in Dockfer file are hence now:

```
ARG SPACEPY=/pipeline/lib/spacepy
ARG SPACEPY_DATA=/usr/local/lib/python3.8/site-packages/spacepy/data
RUN mkdir -p $SPACEPY/.spacepy && cp -r $SPACEPY_DATA $SPACEPY/.spacepy/.  && chmod -R 2777 $SPACEPY
```

**Comment by xbonnin** [comment]
Ok I talked a little bit too fast!

A colleague working on spacepy with the same Docker container has the following error message now:

```
  File "/usr/local/lib/python3.8/site-packages/poppy/pop/scripts/scripts.py", line 76, in load_plugins
    plugin.load()
  File "/usr/local/lib/python3.8/site-packages/poppy/core/plugin.py", line 225, in load
    self._check_module("commands")
  File "/usr/local/lib/python3.8/site-packages/poppy/core/plugin.py", line 58, in _check_module
    importlib.import_module(name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/site-packages/roc/film/commands.py", line 16, in <module>
    from roc.film.tasks.file_helpers import get_output_dir, get_products_dir, is_output_dir
  File "/usr/local/lib/python3.8/site-packages/roc/film/tasks/__init__.py", line 8, in <module>
    from roc.film.tasks.l1_sbm import *
  File "/usr/local/lib/python3.8/site-packages/roc/film/tasks/l1_sbm.py", line 8, in <module>
    from spacepy.pycdf import CDF
  File "/usr/local/lib/python3.8/site-packages/spacepy/__init__.py", line 390, in <module>
    _read_config(rcfile)
  File "/usr/local/lib/python3.8/site-packages/spacepy/__init__.py", line 359, in _read_config
    with open(rcfile, 'w') as cf:
PermissionError: [Errno 13] Permission denied: '/pipeline/lib/spacepy/.spacepy/spacepy.rc'
```

Default USER of the Docker container is indeed me, not her (since we do not want to call the docker container as root).
By default the spacepy.rc is then only writable by me (or root).

**Comment by xbonnin** [comment]
Ok I think I found a dirty but working solution to use spacepy in the Docker container with multiple users.

To avoid error, I add the following steps in the Dockerfile (used when building the Docker image):

1. I create the .spacepy/ sub-folder into a common location, here $SPACEPY=/pipeline/lib/spacepy (to avoid "$HOME/.spacepy folder not found" error)
2. I create the spacepy.rc config file in the .spacepy/ sub-folder. The file only contains the [spacepy] section (to avoid "no [spacepy] section" error message)
3. I copy spacepy data into .spacepy/ sub-folder (to avoid "spacepy data not found" error)
4. I ensure that .spacepy/ sub-folder has read/write access for all users (to avoid "permission denied" error)

Commands in Dockfer file are hence now:

```
ARG SPACEPY=/pipeline/lib/spacepy
ARG SPACEPY_DATA=/usr/local/lib/python3.8/site-packages/spacepy/data
RUN mkdir -p $SPACEPY/.spacepy && echo "[spacepy]" > $SPACEPY/.spacepy/spacepy.rc && cp -r $SPACEPY_DATA $SPACEPY/.spacepy/.  && chmod -R 2777 $SPACEPY/.spacepy

```

N.B. I add also to option -e SPACEPY=/pipeline/lib/spacepy in the `docker-compose run` command to make sure the variable is taken account.

**Comment by jtniehof** [comment]
I hate adding more to the 0.2.3 list, but there's a number of little annoyances you've documented here (thanks!) that we should resolve, basically need to work with having lots of different "partial states" on that file.

The good news is that the welcome message isn't printed anymore (#447) so there's a lot less to that dance, don't need to make the rcfile.

The `spacepy.rc` permissions are going to be based on your umask--we don't set them. I need to double-check that other things in .spacepy are just limited by umask and not explicitly set otherwise.

I also think we should make the directory if `$SPACEPY` is set, since that's a pretty specific ask.

**Comment by xbonnin** [comment]
Sorry to add you more work ;-).

Our case is may be not the usual way to use spacepy (i.e., as a single user), but it is always interesting to enlarge the possibility of usage. 
In the present case, calling spacepy in a data processing pipeline hosted in a Docker container and run/maintained by several people.

ps. Thanks for the welcome message, much more appreciated to not have it appearing in our log file each time we run our Docker container.
