### ISSUE TITLE
Need requirements.txt for pip

### ISSUE THREAD

**Issue by balarsen** [spacepy/spacepy#38]
We need a `requirements.txt` file for pip.   We currently cannot take a bare python install and do a `pip install spacepy` even can't do `pip install https://github.com/spacepy/spacepy`

This file is a good way to document version requirements and could ever interface with the CI having several requirements.txt files in the repo and calling them in the CI rather than a hard code.

**Comment by jtniehof** [comment]
This worked just fine before, although pip may have changed...can you link the docs that require `requirements.txt`? This used to be handled by the `install_requires` kwarg in setuptools.

**Comment by jtniehof** [comment]
I'm going to mark this for 0.1.7 with the understanding it's "pip needs to work for 0.1.7" not any particular implementation of "works".

**Comment by balarsen** [comment]
Just some more info: `install_requires` is not doing it.

```
> virtualenv TST
> source TST/bin/activate
> pip install spacepy
Collecting spacepy
  Downloading https://files.pythonhosted.org/packages/f7/10/4a9a43014d25c1ce08aad136da2515eb120a26105dec5e8f42b5986c22a3/spacepy-0.1.6.tar.gz (11.1MB)
    100% |████████████████████████████████| 11.1MB 2.4MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/ct/p8l3b7lx71sdd4g8vc7bcgdm0000gr/T/pip-install-dlkujyon/spacepy/setup.py", line 24, in <module>
        from numpy.distutils.core import setup
    ModuleNotFoundError: No module named 'numpy'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/ct/p8l3b7lx71sdd4g8vc7bcgdm0000gr/T/pip-install-dlkujyon/spacepy/
```

**Comment by drsteve** [comment]
Under what circumstances is this an issue? I have no trouble getting spacepy installed via ```pip``` (in a clean virtualenv):

```
(clean) user:/mnt/projects/virtualenvs/clean$ pip install spacepy
Collecting spacepy
Collecting numpy>=1.4 (from spacepy)
  Downloading https://files.pythonhosted.org/packages/40/c5/f1ed15dd931d6667b40f1ab1c2fe1f26805fc2b6c3e25e45664f838de9d0/numpy-1.15.2-cp27-cp27mu-manylinux1_x86_64.whl (13.8MB)
    100% |████████████████████████████████| 13.8MB 1.2MB/s 
Collecting ffnet (from spacepy)
Collecting networkx (from spacepy)
  Downloading https://files.pythonhosted.org/packages/f3/f4/7e20ef40b118478191cec0b58c3192f822cace858c19505c7670961b76b2/networkx-2.2.zip (1.7MB)
    100% |████████████████████████████████| 1.7MB 9.2MB/s 
Collecting matplotlib>=0.99 (from spacepy)
  Using cached https://files.pythonhosted.org/packages/59/08/04933377dc4500e3698e93f9113dc3624874e0914f4c85767ecb5b389084/matplotlib-2.2.3-cp27-cp27mu-manylinux1_x86_64.whl
Collecting scipy>=0.7 (from spacepy)
  Using cached https://files.pythonhosted.org/packages/2a/f3/de9c1bd16311982711209edaa8c6caa962db30ebb6a8cc6f1dcd2d3ef616/scipy-1.1.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting python-dateutil (from spacepy)
  Using cached https://files.pythonhosted.org/packages/cf/f5/af2b09c957ace60dcfac112b669c45c8c97e32f94aa8b56da4c6d1682825/python_dateutil-2.7.3-py2.py3-none-any.whl
Collecting h5py (from spacepy)
  Using cached https://files.pythonhosted.org/packages/33/0c/1c5dfa85e05052aa5f50969d87c67a2128dc39a6f8ce459a503717e56bd0/h5py-2.8.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting decorator>=4.3.0 (from networkx->spacepy)
  Using cached https://files.pythonhosted.org/packages/bc/bb/a24838832ba35baf52f32ab1a49b906b5f82fb7c76b2f6a7e35e140bac30/decorator-4.3.0-py2.py3-none-any.whl
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 (from matplotlib>=0.99->spacepy)
  Downloading https://files.pythonhosted.org/packages/2b/4a/f06b45ab9690d4c37641ec776f7ad691974f4cf6943a73267475b05cbfca/pyparsing-2.2.2-py2.py3-none-any.whl (57kB)
    100% |████████████████████████████████| 61kB 19.9MB/s 
Collecting backports.functools-lru-cache (from matplotlib>=0.99->spacepy)
  Using cached https://files.pythonhosted.org/packages/03/8e/2424c0e65c4a066e28f539364deee49b6451f8fcd4f718fefa50cc3dcf48/backports.functools_lru_cache-1.5-py2.py3-none-any.whl
Collecting subprocess32 (from matplotlib>=0.99->spacepy)
Collecting pytz (from matplotlib>=0.99->spacepy)
  Using cached https://files.pythonhosted.org/packages/30/4e/27c34b62430286c6d59177a0842ed90dc789ce5d1ed740887653b898779a/pytz-2018.5-py2.py3-none-any.whl
Collecting six>=1.10 (from matplotlib>=0.99->spacepy)
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting kiwisolver>=1.0.1 (from matplotlib>=0.99->spacepy)
  Using cached https://files.pythonhosted.org/packages/3a/62/a8c9bef3059d55ab38e41fe9cba4fad773bfc04e47290bab84db1c18262e/kiwisolver-1.0.1-cp27-cp27mu-manylinux1_x86_64.whl
Collecting cycler>=0.10 (from matplotlib>=0.99->spacepy)
  Using cached https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools in ./lib/python2.7/site-packages (from kiwisolver>=1.0.1->matplotlib>=0.99->spacepy) (40.4.3)
Building wheels for collected packages: networkx
  Running setup.py bdist_wheel for networkx ... done
  Stored in directory: /home/smorley/.cache/pip/wheels/68/f8/29/b53346a112a07d30a5a84d53f19aeadaa1a474897c0423af91
Successfully built networkx
Installing collected packages: numpy, scipy, decorator, networkx, ffnet, pyparsing, backports.functools-lru-cache, subprocess32, pytz, six, python-dateutil, kiwisolver, cycler, matplotlib, h5py, spacepy
Successfully installed backports.functools-lru-cache-1.5 cycler-0.10.0 decorator-4.3.0 ffnet-0.8.3 h5py-2.8.0 kiwisolver-1.0.1 matplotlib-2.2.3 networkx-2.2 numpy-1.15.2 pyparsing-2.2.2 python-dateutil-2.7.3 pytz-2018.5 scipy-1.1.0 six-1.11.0 spacepy-0.1.6 subprocess32-3.5.2
```

The virtualenv has an up to date pip.

```
(clean) user:/mnt/projects/virtualenvs/clean$ pip --version
pip 18.1 from /mnt/projects/virtualenvs/clean/local/lib/python2.7/site-packages/pip (python 2.7)
```

**Comment by balarsen** [comment]
Interesting, my python 3.7 setup died with the message I gave in #38, not
finding numpy.

**Comment by drsteve** [comment]
Okay, I can reproduce this in a clean Python 3 (3.5.2) virtualenv.
```
~/.local/bin/virtualenv -p python3 py3-clean
cd py3-clean/
source bin/activate
pip3 install spacepy
```
then I get.
```
Collecting spacepy
  Using cached https://files.pythonhosted.org/packages/f7/10/4a9a43014d25c1ce08aad136da2515eb120a26105dec5e8f42b5986c22a3/spacepy-0.1.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-zim6lgzj/spacepy/setup.py", line 24, in <module>
        from numpy.distutils.core import setup
    ImportError: No module named 'numpy'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-zim6lgzj/spacepy/
```

Our ```setup.py``` imports ```numpy``` right off the bat, so under python2 it must be finding the information about dependencies without actually running setup (otherwise it would fail too). It shouldn't be necessary to specify a ```requirements.txt``` when installing with ```pip```. Maybe pip3 is doing something slightly different under the hood from pip2?

Either way, I'm pretty sure that's a new ticket "pip installs fails to resolve dependencies under python 3", rather than wanting a ```requirements.txt```. The latter is nice (and maybe a ```requirements-doc.txt``` if folks want to build docs), but I don't think is required; the former is a big python 3 compatibility issue and probably needs a restructuring of our ```setup.py```.
