### ISSUE TITLE
datamanager.rebin ValueError: shapes not aligned when usign 1d bindata

### ISSUE THREAD

**Issue by asher-m** [spacepy/spacepy#419]
When using datamanager.rebin with 1d bindata, a ValueError is raised by numpy that array shapes aren't aligned.  Without going into too much detail as to what I think the specifics are (as, admittedly, I'm probably wrong), here's a minimum working example:

### Minimal example to reproduce issue:
```
import numpy
import spacepy.datamanager


data = numpy.ones((10, 10))
bindata = numpy.array([0.05 + 0.1 * i for i in range(10)])
edges = numpy.linspace(0, 1, 30 + 1)

rebinned = spacepy.datamanager.rebin(data, bindata, edges, axis=1, bintype='count')
```

### Traceback:
```
$ python rebin_problem.py
This unreleased version of SpacePy is not supported by the SpacePy team.
Traceback (most recent call last):
  File "rebin_problem.py", line 18, in <module>
    rebinned = spacepy.datamanager.rebin(data, bindata, edges, axis=1, bintype='count')
  File "/home/asher/.local//lib//python2.7/site-packages/spacepy/datamanager.py", line 1108, in rebin
    counts = numpy.matmul(select, ~idx)[..., 0]
ValueError: shapes (10,30,1) and (10,10,1) not aligned: 1 (dim 2) != 10 (dim 1)
```

### OS, Python version, and dependency version information:
I'm on Ubuntu 16.04x64 (Linux 4.4.0) with spacepy 22ceeef, and numpy 1.11.0.  I've been able to reproduce the issue in Python 2.7.12 and 3.5.2.

On Windows with Python 3.7.6 and numpy 1.18.1 I get a slightly different error message but to the same effect.

### More information:
Forcing rebin to align the axis by padding out bindata with a degenerate dimension fixes the problem:
```
import numpy
import spacepy.datamanager


data = numpy.ones((10, 10))
bindata = numpy.array([0.05 + 0.1 * i for i in range(10)])
bindata = bindata[None, ...]  # adding degenerate dimensions to match shape of data fixes the problem
edges = numpy.linspace(0, 1, 30 + 1)

rebinned = spacepy.datamanager.rebin(data, bindata, edges, axis=1, bintype='count')
```

Also, for what it's worth, the error was initially encountered when using rebin's default `bintype='mean'`.  It's hard to figure out what a correct answer from that looks like, however, so using `'count'` for debugging purposes simplifies things.

**Comment by jtniehof** [comment]
Contrived examples are fine, thanks. Note the issue here pertains to having two dimensions on the data to be rebinned which are the same size, and the one desired to be rebinned is the *second* one.
