### ISSUE TITLE
test_pybats.TestBats2d.testPlotting failure

### ISSUE THREAD

**Issue by jtniehof** [spacepy/spacepy#421]
A pybats test is failing (this is probably numpy version dependent).

### Minimal example to reproduce issue:

```
python3 test_pybats.py TestBats2d.testPlotting
```

### Error message/Traceback:

```
======================================================================
ERROR: testPlotting (__main__.TestBats2d)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_pybats.py", line 224, in testPlotting
    self.mhd.add_stream_scatter('ux','uz',target=ax,narrow=1)
  File "/home/jtniehof/.local//lib//python3.5/site-packages/spacepy/pybats/bats.py", line 1553, in add_stream_scatter
    method=method)
  File "/home/jtniehof/.local//lib//python3.5/site-packages/spacepy/pybats/bats.py", line 1355, in get_stream
    maxPoints=maxPoints, method=method, extract=extract)
  File "/home/jtniehof/.local//lib//python3.5/site-packages/spacepy/pybats/bats.py", line 455, in __init__
    self.treetrace(bats, maxPoints=maxPoints)
  File "/home/jtniehof/.local//lib//python3.5/site-packages/spacepy/pybats/bats.py", line 588, in treetrace
    for i in range(1, xbwd.size):
AttributeError: 'list' object has no attribute 'size'

----------------------------------------------------------------------
Ran 1 test in 0.229s

FAILED (errors=1)
```

### OS, Python version, and dependency version information:
```
Linux-4.4.0-98-generic-x86_64-with-Ubuntu-16.04-xenial
sys.version_info(major=3, minor=5, micro=2, releaselevel='final', serial=0)
numpy=1.11.0
scipy=0.17.0
matplotlib=1.5.1
```

### Version of SpacePy
Current master (22ceeef889d36cf9a7717206610c7cc814262c7a)

**Comment by jtniehof** [comment]
### Works
Python 2.7, numpy 1.16.6, scipy 1.2.3, matplotlib 2.2.5
Python 3.5, numpy 1.18.5, scipy 1.4.1, matplotlib 3.0.3

### Does not work
Python 2.7, numpy 1.10.4, scipy 0.11.0, matplotlib 1.5.3
Python 3.5, numpy 1.10.4, scipy 0.17.1, matplotlib 1.5.3

**Comment by jtniehof** [comment]
Python 3.8, numpy 1.19.2, scipy 1.5.2, matplotlib 2.0.2 works.
Python 3.8, numpy 1.19.2, scipy 1.5.2, matplotlib 1.5.3 does not work.

We could in theory bump to matplotlib 2.0 requirement...that would lose us Ubuntu 16.04 support. We're not supporting 16.04 anymore, but this would be the first thing to actually break that.

I'm going to see if I can't get it fixed, though.

**Comment by jtniehof** [comment]
xstart, ystart, return from bats.find_block on working:
```
-3.0 0 49
2.7624365015594066 -0.7965987539861115 48
2.516617963678233 1.3900572020215658 59
1.7930999665391265 2.2473133982596605 59
1.3202169589354638 2.5539483513452645 59
1.0635290394779295 2.6710542828978885 59
0.9311855505087185 2.7200217775826308 59
0.8641524187995874 2.742054995269574 59
0.8304381168557529 2.752453003063462 59
0.8135337499638697 2.7574966614068135 59
0.8075158941883173 2.75926495295998 59
-1.3850788054943555 2.5193613679999003 58
-0.31270299270753943 2.85794363806422 58
-0.865606866294909 2.7415962053196505 58
-0.592020026884358 2.813385378466278 58
-0.729696828330184 2.780857338794076 58
-0.7978933692364805 2.762062847099692 58
-0.7638529054438118 2.771669846652925 58
-0.7808879114377086 2.7669186959089442 58
2.5 0.0 48
-2.5 3.061616997868383e-16 58
2.4899182496933667 0.2242924649735682 59
-2.4867117579948768 -0.2574191769274958 49
2.459754312124865 0.44677592144511813 59
-2.4469882938799765 -0.512101835199173 49
2.4097514715239567 0.6656559512902478 59
-2.381251891658852 -0.7613405469769358 49
2.3403130208134924 0.8791671994625514 59
-2.2902013683085105 -1.0024857568054648 49
2.2519990088908655 1.0855876122886443 59
-2.174804644940131 -1.2329739479594974 49
2.1455217236095003 1.283252326520283 59
-2.036288457223088 -1.450354894148331 49
2.0217399468922252 1.470567097122815 59
-1.8761253144565888 -1.6523177068757589 49
1.8816520283113398 1.6460211554994733 59
-1.6960178459217397 -1.8367154015565348 49
1.7263878329997306 1.808199394444787 59
-1.4978807009215986 -2.0015877212369735 49
1.557199628836352 1.9557937815505824 59
-1.283820194922536 -2.1451819752899897 49
1.3754519864045656 2.0876139090108916 59
-1.0561119181705194 -2.2659716715568594 49
1.1826107731842246 2.202596594737359 59
-0.8171765448159868 -2.362672743865008 49
0.9802313307437417 2.299814457348321 59
-0.5695540997107119 -2.434257202413648 49
0.7699459302878214 2.378483395870827 59
-0.3158769564358665 -2.4799640619155783 49
0.6401483457563201 2.416652663380786 59
-0.19960213207838678 -2.492019058689111 49
0.33200449071352495 2.477856537038828 59
0.03174925946264996 -2.4997983887752975 48
0.018617697802254553 2.499930675304526 59
0.262828450712167 -2.4861458536248917 48
-0.2950631014720674 2.482526488509173 58
0.4916542986675635 -2.4511785023946557 48
-0.6040843327237606 2.42591881953162 58
0.7162649792241194 -2.3951961254847323 48
-157.80716266637143 14.87371799730991 5
-148.29875354426332 -60.04694965130942 2
-159.09021093388353 72.01268135303701 5
25.546312241991444 108.92997754508266 16
-36.32278773446788 111.82779237060504 17
-124.6752705848258 -83.11527604326444 2
-62.842564671801966 -112.79609503482337 10
-37.7182096948155 -75.76965697721934 10
-91.2242198971957 17.50819912196414 14
-66.097349056085 44.06071146289875 14
-180.26951149819283 -2.7416646952102894 2
-35.79087556956392 85.4712535837881 17
-41.63268011329035 112.92213738279727 17
-111.04617712433327 8.114498339779288 5
-203.17653622180117 -114.64100490202448 2
-8.895581148789034 -42.64274968791254 46
-150.14242876368183 27.569180599663923 5
-83.73449003662031 42.84911449960478 14
0.21923613843415524 -18.94550105631727 48
-11.023131164243068 19.417430058096187 58
-159.7622082783688 -18.779422469428 2
-173.92766831926212 56.73411375489482 5
2.798829830440269 57.188774849280236 60
-61.50887365627736 -74.34033629000659 10
-193.0246812841037 -30.94735027602097 2
-212.84020966933338 9.72003034894334 5
-202.70491953852172 51.73464132391078 5
-167.5345945672641 49.9153563102945 5
-92.55567618915948 -96.87696351036367 10
-190.912622747738 -93.47617724861868 2
-109.5394049558334 -4.498868805265303 2
16.0100010153771 89.0773146278828 16
-69.68561706102372 93.38676450125513 17
-127.21248381399397 45.50068284183308 5
-193.0006168435499 -42.98449401792983 2
5.523122530477934 -1.7330535131720382 48
13.267278875004735 -9.023348582082036 48
-210.95038782784565 88.75785718140023 5
-205.65732055925548 6.988425293325804 5
-28.828238835110398 -92.35541166383865 11
-165.47513309048725 90.05995490312253 5
-170.0808840843914 -18.892852763120487 2
-11.949487793399328 -73.6254646228057 11
-175.8825186593803 25.918461670681353 5
-160.83562160742366 59.32139197171844 5
-3.526810963048348 -69.40267661567158 11
-73.19966737363 62.18133775477426 14
-78.26052103906383 -109.87275379095882 10
-65.41928334136222 -36.8165309228651 13
-55.44707975357281 85.19853514833798 17
-16.770967792014176 -111.1093030752871 11
-88.56160597607297 -40.174568877601956 13
-218.85166689090968 -48.54080892150017 2
-46.53138459479612 -38.309071170314354 13
-73.78171846758218 42.091366407663315 14
-31.412458505336303 53.17982675495969 61
-20.63001811079971 117.02410204264373 16
-140.79097914153948 -122.88002898893154 2
-51.16746265518947 85.06345920881779 17
-145.1535121130216 16.164453863116904 5
-51.70114410071474 -86.5670187739636 10
-126.81028654067663 43.18218895779907 5
-64.95008590703694 44.44419921768471 14
-147.91998053901014 86.10008227120522 5
-147.69402307433802 -12.989694272695232 2
-28.77798456033989 118.61122630050727 16
-3.428570514104109 -55.27877418033543 46
-18.078690544980674 55.17148271709297 61
-142.44603686370493 32.066216042592 5
23.52814308179873 41.30184790383856 60
-39.935210894008605 -18.167801592694914 13
-214.3710926395247 84.65174080692967 5
-4.895381238738764 95.03303056077436 16
-73.57696834488482 77.99348236197608 17
-59.746459672984 118.3698519943517 17
14.69188066000686 -46.08341495435552 47
-196.8186044187927 1.2088192199304757 5
-211.57424501189678 123.73735008656155 5
-171.43735789081222 -36.34400502994984 2
-56.70371563447125 -39.92273090681725 13
-166.8239166563021 -27.500579208750224 2
-61.93478548386858 -70.7505252209634 10
-178.4639314145001 122.58932373448124 5
14.486544656649727 50.501775941639806 60
-45.6573109749462 -50.12787408836189 13
-192.46688853322482 -44.53174741548956 2
-190.43991089038227 -96.45451974686738 2
-6.281437580853122 80.95086730289543 16
-45.92755433766942 -121.4779816246961 10
-171.097923728526 -45.48434447856235 2
-12.193258634757427 59.800434259718884 61
-133.95037139329213 67.95116467391415 5
-29.19620142139658 -93.04968988518671 11
-46.66389815504883 77.7350032142079 17
-139.45750335238688 50.52781837796525 5
-167.12895203312166 31.96597535044296 5
-62.3455368230928 107.66649301096419 17
-149.03847486895873 81.55993169063362 5
-0.9538986845293778 118.43848230189613 16
11.152540031947666 -27.650614182667297 48
```

not working:
```
-3.0 0 49
2.7624365015594066 -0.7965987539861115 48
2.516617963678233 1.3900572020215658 59
1.7930999665391265 2.2473133982596605 59
1.3202169589354638 2.5539483513452645 59
1.0635290394779295 2.6710542828978885 59
0.9311855505087185 2.7200217775826308 59
0.8641524187995874 2.742054995269574 59
0.8304381168557529 2.752453003063462 59
0.8135337499638697 2.7574966614068135 59
0.8075158941883173 2.75926495295998 59
-1.3850788054943555 2.5193613679999003 58
-0.31270299270753943 2.85794363806422 58
-0.865606866294909 2.7415962053196505 58
-0.592020026884358 2.813385378466278 58
-0.729696828330184 2.780857338794076 58
-0.7978933692364805 2.762062847099692 58
-0.7638529054438118 2.771669846652925 58
-0.7808879114377086 2.7669186959089442 58
2.5 0.0 48
-2.5 3.061616997868383e-16 58
2.4899182496933667 0.2242924649735682 59
-2.4867117579948768 -0.2574191769274958 49
2.459754312124865 0.44677592144511813 59
-2.4469882938799765 -0.512101835199173 49
2.4097514715239567 0.6656559512902478 59
-2.381251891658852 -0.7613405469769358 49
2.3403130208134924 0.8791671994625514 59
-2.2902013683085105 -1.0024857568054648 49
2.2519990088908655 1.0855876122886443 59
-2.174804644940131 -1.2329739479594974 49
2.1455217236095003 1.283252326520283 59
-2.036288457223088 -1.450354894148331 49
2.0217399468922252 1.470567097122815 59
-1.8761253144565888 -1.6523177068757589 49
1.8816520283113398 1.6460211554994733 59
-1.6960178459217397 -1.8367154015565348 49
1.7263878329997306 1.808199394444787 59
-1.4978807009215986 -2.0015877212369735 49
1.557199628836352 1.9557937815505824 59
-1.283820194922536 -2.1451819752899897 49
1.3754519864045656 2.0876139090108916 59
-1.0561119181705194 -2.2659716715568594 49
1.1826107731842246 2.202596594737359 59
-0.8171765448159868 -2.362672743865008 49
0.9802313307437417 2.299814457348321 59
-0.5695540997107119 -2.434257202413648 49
0.7699459302878214 2.378483395870827 59
-0.3158769564358665 -2.4799640619155783 49
0.6401483457563201 2.416652663380786 59
-0.19960213207838678 -2.492019058689111 49
0.33200449071352495 2.477856537038828 59
0.03174925946264996 -2.4997983887752975 48
0.018617697802254553 2.499930675304526 59
0.262828450712167 -2.4861458536248917 48
-0.2950631014720674 2.482526488509173 58
0.4916542986675635 -2.4511785023946557 48
-0.6040843327237606 2.42591881953162 58
0.7162649792241194 -2.3951961254847323 48
-11.050591126100585 38.391646017367776 61
34.70101955460012 123.62295291763735 False
```

The divergence happens on step 60. Step 59 has same xstart, ystart, and block, whereas step 60 has different xstart, ystart, and thus block.

**Comment by jtniehof** [comment]
This test was added in b9135a9e3e4dba113131cdc52f948a8abf9725eb and that commit doesn't work with MPL 1.5.3, so this isn't a regression. Probably never worked but there wasn't a test for it.

**Comment by jtniehof** [comment]
Attached are the test plots from old matplotlib (up to the point where add_stream_scatter fails) and the new matplotlib. The contour and field lines look the same. The complete lack of flow deviation looks weird to me. @spacecataz , does this look right?
![old_matplotlib](https://user-images.githubusercontent.com/196315/94048200-23c69400-fda1-11ea-8f2c-e07b2528e89e.png)
![new_matplotlib](https://user-images.githubusercontent.com/196315/94048212-29bc7500-fda1-11ea-9550-532ce9a6f202.png)

**Comment by jtniehof** [comment]
Ah, if I plot just the streamlines without the contour and field there's some deviation at Earth that's more readily visible, out to maybe 3Re. Watching the streamlines blow right through the field line still seems weird.

**Comment by jtniehof** [comment]
Because the limits are different, I'm guessing the problem is the selection of start points in add_stream_scatter (since the start points become the xstart/ystart). So there's likely an issue with get_stream not raising an easily-understandable error if the start points are outside of the actual data, and then with choosing the default limits (starting around line 1524 of bats.py). My suggestion would be to choose the more restrictive of the axis limits and the input data, e.g.:
```python
        if xlim == None:
            if use_ax_lims:
                axlims = ax.get_xlim()
                xlim = [max(self[dims[0]].min(), axlims[0]),
                        min(self[dims[0]].max(), axlims[1])]
            else:
                xlim = [self[dims[0]].min(), self[dims[0]].max()]
```
@spacecataz , does that sound reasonable?

**Comment by spacecataz** [comment]
This solution looks good, and is a case I hadn't previously considered.
