### ISSUE TITLE
pycdf tracebacks when fail to open CDF

### ISSUE THREAD

**Issue by jtniehof** [spacepy/spacepy#429]
This is somewhat amusing, but I accidentally opened a CDF passing in a list instead of a filename and the resulting traceback fails because it tries to display the repr of the CDF, which relies on the `_opened` attribute existing. This shouldn't be brutally hard to fix....

### Minimal example to reproduce issue:

```sh
python -c "import spacepy.pycdf; spacepy.pycdf.CDF(['hi'])"
```

### Error message/Traceback:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jtniehof/.local//lib//python2.7/site-packages/spacepy/pycdf/__init__.py", line 1744, in __init__
    'pathname must be string-like: {0}'.format(pathname))
ValueError: pathname must be string-like: ['hi']
Exception AttributeError: "'CDF' object has no attribute '_opened'" in <object repr() failed> ignored
```

### OS, Python version, and dependency version information:

```
Linux-4.4.0-98-generic-x86_64-with-Ubuntu-16.04-xenial
sys.version_info(major=2, minor=7, micro=12, releaselevel='final', serial=0)
numpy=1.11.0
scipy=0.17.0
matplotlib=1.5.1

### Version of SpacePy
Current master from github (de60fc3d101a5827c518f0fb33b7a72421f4617f)

**Comment by balarsen** [comment]
Really funny this has different behaviors... 

As you note
```
$ python -c "import spacepy.pycdf; spacepy.pycdf.CDF(['hi'])"
Traceback (most recent call last):
  File "/home/balarsen/miniconda3/envs/python3/lib/python3.8/site-packages/spacepy/pycdf/__init__.py", line 1741, in __init__
    self.pathname = pathname.encode()
AttributeError: 'list' object has no attribute 'encode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/balarsen/miniconda3/envs/python3/lib/python3.8/site-packages/spacepy/pycdf/__init__.py", line 1743, in __init__
    raise ValueError(
ValueError: pathname must be string-like: ['hi']
Exception ignored in: <function CDF.__del__ at 0x7f6ec5e03c10>
Traceback (most recent call last):
  File "/home/balarsen/miniconda3/envs/python3/lib/python3.8/site-packages/spacepy/pycdf/__init__.py", line 1770, in __del__
    if self._opened:
AttributeError: 'CDF' object has no attribute '_opened'
```

From inside ipython
```
$ ipython
In [1]: import spacepy.pycdf
In [2]: spacepy.pycdf.CDF(['hi'])
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/miniconda3/envs/python3/lib/python3.8/site-packages/spacepy/pycdf/__init__.py in __init__(self, pathname, masterpath, create, readonly)
   1740         try:
-> 1741             self.pathname = pathname.encode()
   1742         except AttributeError:

AttributeError: 'list' object has no attribute 'encode'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-2-700853c5cbd7> in <module>
----> 1 spacepy.pycdf.CDF(['hi'])

~/miniconda3/envs/python3/lib/python3.8/site-packages/spacepy/pycdf/__init__.py in __init__(self, pathname, masterpath, create, readonly)
   1741             self.pathname = pathname.encode()
   1742         except AttributeError:
-> 1743             raise ValueError(
   1744                 'pathname must be string-like: {0}'.format(pathname))
   1745         self._handle = ctypes.c_void_p(None)

ValueError: pathname must be string-like: ['hi']
```


Linux-4.4.0-18362-Microsoft-x86_64-with-glibc2.10
sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)
numpy=1.19.5
scipy=1.6.0
matplotlib=3.3.3

**Comment by jtniehof** [comment]
It has to do with how tracebacks are formatted and whether the `__repr__` is called in the traceback (and what happens if the `__repr__` raises an exception.) If you use normal python command line (not ipython), the exception ignored pops up on exit.
