### ISSUE TITLE
Deleting leapseconds file makes it impossible to download

### ISSUE THREAD

**Issue by jtniehof** [spacepy/spacepy#435]
This is hilarious...importing toolbox imports time, which reads the leapseconds file. So if the leapseconds file doesn't exist, importing toolbox to run `update` fails. Ooops.

This is probably going to require that time gracefully assumes no leapseconds and reloads itself after `update` downloads leapseconds.

### Minimal example to reproduce issue:

```sh
rm ~/.spacepy/data/tai-utc.dat
python -e "import spacepy.toolbox; spacepy.toolbox.update(leapsecs=True)"
```

### Error message/Traceback:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jtniehof/.local//lib//python2.7/site-packages/spacepy/toolbox/__init__.py", line 67, in <module>
    from spacepy import time as spt
  File "/home/jtniehof/.local//lib//python2.7/site-packages/spacepy/time.py", line 2573, in <module>
    _read_leaps()
  File "/home/jtniehof/.local//lib//python2.7/site-packages/spacepy/time.py", line 2259, in _read_leaps
    with open(fname) as fh:
IOError: [Errno 2] No such file or directory: '/home/jtniehof/.spacepy/data/tai-utc.dat
```

### OS, Python version, and dependency version information:

```
Linux-4.4.0-98-generic-x86_64-with-Ubuntu-16.04-xenial
sys.version_info(major=2, minor=7, micro=12, releaselevel='final', serial=0)
numpy=1.11.0
scipy=0.17.0
matplotlib=1.5.1
```

### Version of SpacePy
git master (568c0df6a38aabf800bf371adda28471ff4177e4)

**Comment by jtniehof** [comment]
Note that `toolbox.update()` already re-reads the leapsecond file if `time` has already been imported.
