### ISSUE TITLE
Cannot import 'irbempylib

### ISSUE THREAD

**Issue by reedcurtis11** [spacepy/spacepy#507]
My issue is I cannot import the irbempy package from spacepy.

### Minimal example to reproduce issue:
```
from spacepy import irbempy
```

### Error message/Traceback:

```
Traceback (most recent call last):
  File "/PycharmProjects/gpsdata/LStar.py", line 2, in <module>
    from spacepy import irbempy
  File "\PycharmProjects\gpsdata\venv\Lib\site-packages\spacepy\irbempy\__init__.py", line 71, in <module>
    from .irbempy import *
  File "\PycharmProjects\gpsdata\venv\Lib\site-packages\spacepy\irbempy\irbempy.py", line 31, in <module>
    from . import irbempylib as oplib
ImportError: DLL load failed while importing irbempylib: The specified module could not be found.
```

### OS, Python version, and dependency version information:

```
Windows-10-10.0.19041-SP0
sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)
numpy=1.20.1
scipy=1.6.0
matplotlib=3.3.4
```
-->

### Version of SpacePy
I am using SpacePy 0.2.2 downloaded through pip.

Sorry if I am just overlooking something small, but I have looked for a fix and have found nothing.
I have tried:
-uninstalling and reinstalling SpacePy
-trying different versions of SpacePy

Thanks for any help.
-->

**Comment by jtniehof** [comment]
Thanks for reaching out. Can you check a few things for me to help debug this?

Just to confirm, you did `pip install spacepy` from within your venv to install?

Where did you install Python itself from?

Copy and paste the following from within a Python window (ipython is fine) and paste the output in a comment:
```python
import os
import sys
import spacepy
import spacepy.lib

print('maxsize: {:x}'.format(sys.maxsize))
print('libspacepy: {}'.format(spacepy.lib.have_libspacepy))
print('path: {}'.format(os.environ['PATH']))
print('Python path: {}'.format(sys.path))
```

In PycharmProjects\gpsdata\venv\Lib\site-packages\spacepy\irbempy there should be a file named either `irbempylib.cp38-win_amd64.pyd` or `irbempylib.cp38-win32.pyd` ..which is there (or neither!) and what is the size in _bytes_ (not kilobytes.)

That'll give me a point to start from. Thanks.

**Comment by jtniehof** [comment]
I'm wondering if this might be related to https://docs.python.org/3/whatsnew/3.8.html#ctypes . We've been pretty careful about running the tests without the compilers installed and #465 does indicate things have been working for some people on Windows 10 and 3.8+. But based on the Python docs there are probably some things to be done to make it more likely the DLLs will be found.
