### ISSUE TITLE
spacepy.toolbox.update() not working

### ISSUE THREAD

**Issue by Yoshi2112** [spacepy/spacepy#519]
First time trying to use SpacePy for more than just reading data files. I tried running the toolbox.update() function as suggested in the warnings, however it crashed. I originally thought it was due to the NMC site being down/inaccessible for the QD param files. However, after specifying the LANL mirror manually in spacepy.config, it started crashing in the _crawl_yearly() function. A little prodding, and it appears that perhaps the links aren't being extracted properly? When queried, the yearlist is empty.

It's possible this is an error on my machine, however I'm not sure what it would be.

### Minimal example to reproduce issue:
```
import spacepy as sp
sp.config['qd_daily_url'] = r'https://rbsp-ect.lanl.gov/data_pub/QinDenton/'
sp.toolbox.update(QDomni=True)
```

### Error message/Traceback:
```
Traceback (most recent call last):

  File "<ipython-input-5-b3f96e5b1565>", line 1, in <module>
    runfile('D:/Google Drive/Codes/ECT_PSD_plots.py', wdir='D:/Google Drive/Uni/Codes')

  File "C:\Users\iarey\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\iarey\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/Google Drive/Codes/ECT_PSD_plots.py", line 15, in <module>
    sp.toolbox.update(QDomni=True)

  File "C:\Users\iarey\Anaconda3\lib\site-packages\spacepy\toolbox\__init__.py", line 1397, in update
    dailyomnidata = _get_qindenton_daily(cached=cached, startyear=startyear)

  File "C:\Users\iarey\Anaconda3\lib\site-packages\spacepy\toolbox\__init__.py", line 882, in _get_qindenton_daily
    return _assemble_qindenton_daily(datadir)

  File "C:\Users\iarey\Anaconda3\lib\site-packages\spacepy\toolbox\__init__.py", line 904, in _assemble_qindenton_daily
    for k in data[0].keys():

IndexError: list index out of range
```

### OS, Python version, and dependency version information:
```
Windows-10-10.0.19041-SP0
sys.version_info(major=3, minor=7, micro=2, releaselevel='final', serial=0)
numpy=1.20.1
scipy=1.6.1
matplotlib=3.3.4
```

### Version of SpacePy
spacepy-0.2.2 installed via pip

**Comment by jtniehof** [comment]
The NMC site is up and is the preferred site for the Qin-Denton parameters; the LANL one isn't updated. I verified `spacepy.toolbox.update(QDomni=True) ` runs to completion with the default config. If you're still having difficulties with that config we should debug your setup. Often this sort of thing crops up if a proxy is required but not fully configured.

Regarding the traceback when using the LANL source, I can reproduce that. The ViRBO "big" file has been updated through 2020, so the LANL daily files, which are only through 2017, add nothing. I'll change the code to deal more gracefully with that case., and would like to leave this bug open until that fix is merged.

**Comment by Yoshi2112** [comment]
Now that the NMC site is back up (I was getting a 403 error originally at the time of posting), the function works as intended. My issue was likely solely the issue when using the LANL source.

Thanks!
