### ISSUE TITLE
Failure to install spacepy due to 'setuptools.command.bdist_wininst'

### ISSUE THREAD

**Issue by rmcgranaghan** [spacepy/spacepy#530]
Running 

`pip install --upgrade spacepy`

Fails with the ultimate error: 

### Minimal example to reproduce issue: `ModuleNotFoundError: No module named 'setuptools.command.bdist_wininst'`

I have confirmed that setuptools exists, but it appears that bdist is deprecated (https://github.com/pypa/setuptools/issues/2558)

Is there a workaround? None of the versions of spacepy that I have attempted have succeeded. 

My dependencies and versions are: 
Python: 3.9 (in a conda environment)
numpy: 1.19.5
ffnet: 0.8.4

Thank you to this community for all of the work that you do!

```
pip install --upgrade spacepy
```

### Error message/Traceback: 
`ModuleNotFoundError: No module named 'setuptools.command.bdist_wininst'`

Traceback (most recent call last):
```

pip install spacepy
Collecting spacepy
  Using cached spacepy-0.2.2.zip (19.3 MB)
    ERROR: Command errored out with exit status 1:
     command: /Users/ryanmcgranaghan/opt/anaconda3/envs/pythontf/bin/python3.9 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/fr/9svwksbd6h115gvfd3t2xrd00000gq/T/pip-install-ic031riu/spacepy_e94398e1f06547a28ba36aea0c52eff0/setup.py'"'"'; __file__='"'"'/private/var/folders/fr/9svwksbd6h115gvfd3t2xrd00000gq/T/pip-install-ic031riu/spacepy_e94398e1f06547a28ba36aea0c52eff0/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/fr/9svwksbd6h115gvfd3t2xrd00000gq/T/pip-pip-egg-info-mq7k4fzm
         cwd: /private/var/folders/fr/9svwksbd6h115gvfd3t2xrd00000gq/T/pip-install-ic031riu/spacepy_e94398e1f06547a28ba36aea0c52eff0/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/fr/9svwksbd6h115gvfd3t2xrd00000gq/T/pip-install-ic031riu/spacepy_e94398e1f06547a28ba36aea0c52eff0/setup.py", line 55, in <module>
        from setuptools.command.bdist_wininst import bdist_wininst as _bdist_wininst
    ModuleNotFoundError: No module named 'setuptools.command.bdist_wininst'
```

### OS, Python version, and dependency version information:
```
>>> print(platform.platform())
macOS-10.15.7-x86_64-i386-64bit
>>> print(sys.version_info)
sys.version_info(major=3, minor=9, micro=2, releaselevel='final', serial=0)
>>> print('numpy={0}'.format(numpy.__version__))
numpy=1.20.2
>>> print('scipy={0}'.format(scipy.__version__))
scipy=1.6.2
>>> print('matplotlib={0}'.format(matplotlib.__version__))
```

### Version of SpacePy
spacepy-0.2.2.zip using pip

**Comment by drsteve** [comment]
Thanks for the report @rmcgranaghan 

While this is deprecated in 3.9 it's not slated for removal until 3.10, so I'm a little confused by this. Unfortunately I can't test on Mac so perhaps @balarsen or @spacecataz can check this out when they get a minute (I suspect neither will be available until next week though).

If you're having trouble with the latest version from PyPI (i.e., `pip install spacepy`) then you might try installing from the repository so you get the latest version. Options here are:
1. Replace your pip command with `pip install git+https://github.com/spacepy/spacepy`. (Details at https://spacepy.github.io/install_mac.html)
2. Either clone or download the repo (smash the green button on the main github page) and then install with `python setup.py install`

**Comment by rmcgranaghan** [comment]
Thanks for the response @drsteve - this was the guidance I needed. 

For traceability: Trying to install from the downloaded repo informed me that I was missing Numpydoc and Sphinx requirements. After running `pip install numpydoc` I was able to install spacepy. I was unable to uncover that missing dependency from the traceback of the `pip install spacepy` attempts.

**Comment by xbonnin** [comment]
Hi,

I don't know if it can be helpful, but I have the same problem when installing spacepy from a Docker image (see last lines in the job.log file attached).

The content of the Dockerfile I use to build image with the `docker build ...` command is given at the bottom, .

[job.log](https://github.com/spacepy/spacepy/files/6639431/job.log)

Solution 2, i.e., cloning and setting up from github repo, seems to work (-->`RUN git clone https://github.com/spacepy/spacepy && cd spacepy && python setup.py install`), but installs 0.2.3rc0, which is not yet supported.

N.B. Surprisingly I have no problem to install spacepy from my local computer with `pip install spacepy` command, not very clear why.

```
FROM python:3.8-buster
ENV PYTHONUNBUFFERED 1

# Install utilities
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get install -y apt-utils
RUN apt-get install -y psmisc

# Install gfortran (required for installing spacepy)
RUN apt-get install -y gfortran

## Install rsync
RUN apt -y install rsync

# Upgrade pip
RUN pip install pip --upgrade

# Install requests (required to install cdf software with for cdf.py)
RUN pip install requests

# Define working directory
RUN mkdir -p /usr/local/cdf
WORKDIR /usr/local/cdf

# Copy content of docker-cdf repo
COPY . /usr/local/cdf

# Get input arguments for installing CDF library
ARG VERSION
ARG URL

# Download and install CDF lib
RUN python /usr/local/cdf/cdf.py ${VERSION:-'3.7.1'} --install-dir /usr/local/cdf --cdf-url ${URL:-'http://cdaweb.gsfc.nasa.gov/pub/software/cdf/dist/cdf{cdf_version}/linux/cdf{cdf_version}-dist-cdf.tar.gz'} --make

# Install numpy (required by spacepy)
RUN pip install numpy

# Install spacepy
RUN pip install spacepy
```

**Comment by balarsen** [comment]
I am seeing the same issues within docker and on my WSL install when trying to install from pip. 

My guess at this point is that pip is doing some weird flags in the install. For some reason my error traceback seem a bit different so I will post it here too, 

```
~$ pip install git+https://github.com/spacepy/spacepy.git
Collecting git+https://github.com/spacepy/spacepy.git
  Cloning https://github.com/spacepy/spacepy.git to /tmp/pip-req-build-yu7gd8wx
  Running command git clone -q https://github.com/spacepy/spacepy.git /tmp/pip-req-build-yu7gd8wx
  Resolved https://github.com/spacepy/spacepy.git to commit c123be273bae7851c0c729395463d402c130a0ee
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /home/balarsen/miniconda3/envs/python3/bin/python /home/balarsen/miniconda3/envs/python3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmp_vzgn871
       cwd: /tmp/pip-req-build-yu7gd8wx
  Complete output (18 lines):
  Traceback (most recent call last):
    File "/home/balarsen/miniconda3/envs/python3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
      main()
    File "/home/balarsen/miniconda3/envs/python3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/balarsen/miniconda3/envs/python3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 117, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-rmwjk8yf/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 154, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/tmp/pip-build-env-rmwjk8yf/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 135, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-rmwjk8yf/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 258, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-rmwjk8yf/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 58, in <module>
      from setuptools.command.bdist_wininst import bdist_wininst as _bdist_wininst
  ModuleNotFoundError: No module named 'setuptools.command.bdist_wininst'
  ----------------------------------------
WARNING: Discarding git+https://github.com/spacepy/spacepy.git. Command errored out with exit status 1: /home/balarsen/miniconda3/envs/python3/bin/python /home/balarsen/miniconda3/envs/python3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmp_vzgn871 Check the logs for full command output.
ERROR: Command errored out with exit status 1: /home/balarsen/miniconda3/envs/python3/bin/python /home/balarsen/miniconda3/envs/python3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmp_vzgn871 Check the logs for full command output.
```
