### ISSUE TITLE
Error raised while trying to import spacepy.pybats

### ISSUE THREAD

**Issue by lukashanson400** [spacepy/spacepy#561]
My issue is ...

### Minimal example to reproduce issue:

```
import spacepy.pybats
```

### Error message/Traceback:

```
Traceback (most recent call last):
  File "<pyshell#25>", line 1, in <module>
    import spacepy.pybats
  File "C:\Users\lukha\AppData\Local\Programs\Python\Python39\lib\site-packages\spacepy\pybats\__init__.py", line 119, in <module>
    import spacepy.plot.apionly
  File "C:\Users\lukha\AppData\Local\Programs\Python\Python39\lib\site-packages\spacepy\plot\__init__.py", line 98, in <module>
    plt.register_cmap(name='plasma', cmap=_plasma)
  File "C:\Users\lukha\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\cm.py", line 149, in register_cmap
    raise ValueError(msg)
ValueError: Trying to re-register the builtin cmap 'plasma'.
```

### OS, Python version, and dependency version information:

```
Windows-10-10.0.19042-SP0
sys.version_info(major=3, minor=9, micro=7, releaselevel='final', serial=0)
numpy=1.21.2
scipy=1.7.1
matplotlib=3.4.3
```

### Version of SpacePy

Version 0.2.2
I downloaded it using pip

**Comment by drsteve** [comment]
New release is out and available via pip. Please let us know if that didn't fix your issue - otherwise we'll close this ticket soon.

**Comment by lukashanson400** [comment]
Awesome, thanks for the assistance. The temporary fix you provided worked as well FYI

Lukas

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
