### ISSUE TITLE
test_datamanager.py: hang in test_path_match_end, other tests fail or error

### ISSUE THREAD

**Issue by jtniehof** [spacepy/spacepy#61]
Python 2.7, 32-bit Windows. `python test_datamanager.py RePathTests.test_path_match_end` hangs indefinitely. Infinite loop in path_split.

**Comment by jtniehof** [comment]
Also Python 3.6, 32-bit Windows.

**Comment by drsteve** [comment]
Confirmed on Python 3.7.1, 32-bit Windows
```
$ python test_datamanager.py
This unreleased version of SpacePy is not supported by the SpacePy team.
F...C:\Users\morle\Anaconda3\envs\spacepy\lib\site-packages\spacepy\datamanager.py:396: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if numpy.shape(fillval) != fillshape:
.....Traceback (most recent call last):
  File "test_datamanager.py", line 346, in <module>
    unittest.main()
  File "C:\Users\morle\Anaconda3\envs\spacepy\lib\unittest\main.py", line 101, in __init__
    self.runTests()
  File "C:\Users\morle\Anaconda3\envs\spacepy\lib\unittest\main.py", line 271, in runTests
    self.result = testRunner.run(self.test)
  File "C:\Users\morle\Anaconda3\envs\spacepy\lib\unittest\runner.py", line 176, in run
    test(result)
  File "C:\Users\morle\Anaconda3\envs\spacepy\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Users\morle\Anaconda3\envs\spacepy\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Users\morle\Anaconda3\envs\spacepy\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Users\morle\Anaconda3\envs\spacepy\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Users\morle\Anaconda3\envs\spacepy\lib\unittest\case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "C:\Users\morle\Anaconda3\envs\spacepy\lib\unittest\case.py", line 615, in run
    testMethod()
  File "test_datamanager.py", line 109, in test_path_match_end
    r = spacepy.datamanager.RePath(r'%y/file%Y%m%d_v\d\.cdf')
  File "C:\Users\morle\Anaconda3\envs\spacepy\lib\site-packages\spacepy\datamanager.py", line 170, in __init__
    self.file_re_split = self.path_split(self.file_re)
  File "C:\Users\morle\Anaconda3\envs\spacepy\lib\site-packages\spacepy\datamanager.py", line 234, in path_split
    res.insert(0, tail)
KeyboardInterrupt
```

The test that hangs is: `test_path_match_end`.
Commenting out that test leads to other errors and failures being reported.
```
$ python test_datamanager.py
This unreleased version of SpacePy is not supported by the SpacePy team.
F...C:\Users\morle\Anaconda3\envs\spacepy\lib\site-packages\spacepy\datamanager.py:396: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if numpy.shape(fillval) != fillshape:
.....EF.
======================================================================
ERROR: test_path_match_start (__main__.RePathTests)
Verify matching beginning of a path regex
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_datamanager.py", line 102, in test_path_match_start
    datetime.datetime(1999, 5, 2), 'start'))
  File "C:\Users\morle\Anaconda3\envs\spacepy\lib\site-packages\spacepy\datamanager.py", line 214, in match
    return re.match('^' + pat + '$', string)
  File "C:\Users\morle\Anaconda3\envs\spacepy\lib\re.py", line 173, in match
    return _compile(pattern, flags).match(string)
  File "C:\Users\morle\Anaconda3\envs\spacepy\lib\re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Users\morle\Anaconda3\envs\spacepy\lib\sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Users\morle\Anaconda3\envs\spacepy\lib\sre_parse.py", line 930, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Users\morle\Anaconda3\envs\spacepy\lib\sre_parse.py", line 426, in _parse_sub
    not nested and not items))
  File "C:\Users\morle\Anaconda3\envs\spacepy\lib\sre_parse.py", line 507, in _parse
    code = _escape(source, this, state)
  File "C:\Users\morle\Anaconda3\envs\spacepy\lib\sre_parse.py", line 399, in _escape
    raise source.error("invalid group reference %d" % group, len(escape) - 1)
re.error: invalid group reference 99 at position 11

======================================================================
FAIL: test_files_matching (__main__.DataManagerClassTests)
Files matching a format
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_datamanager.py", line 63, in test_files_matching
    numpy.testing.assert_array_equal(expected, output, 'Case:' + str(c))
  File "C:\Users\morle\Anaconda3\envs\spacepy\lib\site-packages\numpy\testing\_private\utils.py", line 865, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "C:\Users\morle\Anaconda3\envs\spacepy\lib\site-packages\numpy\testing\_private\utils.py", line 789, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not equal
Case:{'files1': ['rbspa_ect-hope-sci-L2_20150409_v4.0.0.cdf', 'rbspa_ect-hope-sci-L2_20150410_v4.0.0.cdf'], 'files2': ['rbspa_ect-hope-sci-L2_20150409_v4.1.0.cdf'], 'regex': 'rbspa_ect-hope-sci-L2_%Y%m%d_v(\\d\\.){3}cdf', 'dt': None, 'descend': False}
(mismatch 100.0%)
 x: array(['data/datamanager_test/1\\rbspa_ect-hope-sci-L2_20150409_v4.0.0.cdf',
       'data/datamanager_test/1\\rbspa_ect-hope-sci-L2_20150410_v4.0.0.cdf',
       'data/datamanager_test/2\\rbspa_ect-hope-sci-L2_20150409_v4.1.0.cdf'],
      dtype='<U65')
 y: array(['data\\datamanager_test\\1\\rbspa_ect-hope-sci-L2_20150409_v4.0.0.cdf',
       'data\\datamanager_test\\1\\rbspa_ect-hope-sci-L2_20150410_v4.0.0.cdf',
       'data\\datamanager_test\\2\\rbspa_ect-hope-sci-L2_20150409_v4.1.0.cdf'],
      dtype='<U65')

======================================================================
FAIL: test_path_slice (__main__.RePathTests)
Verify slicing on a path
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_datamanager.py", line 84, in test_path_slice
    path, 0, step=2))
AssertionError: 'foo/baz' != 'foo\\baz'
- foo/baz
?    ^
+ foo\baz
?    ^


----------------------------------------------------------------------
Ran 12 tests in 0.193s

FAILED (failures=2, errors=1)
```

**Comment by drsteve** [comment]
At least for the two failed tests it looks like this could be resolved using `os.path.join` to make the test platform-independent.

E.g., 
```
    def test_path_slice(self):
        """Verify slicing on a path"""
        path = os.path.join("foo", "bar", "baz")
        self.assertEqual("bar",
                         spacepy.datamanager.RePath.path_slice(path, 1))
        self.assertEqual(os.path.join("foo", "baz"),
                         spacepy.datamanager.RePath.path_slice(
                             path, 0, step=2))
        self.assertEqual(os.path.join("bar", "baz"),
                         spacepy.datamanager.RePath.path_slice(
                             path, 1, 3))
```

The test that errors appears to be an issue with the path separators. It appears to be fixable by explicitly encoding the search pattern as a raw string when I try the step that fails in pdb, e.g.,
```
ipdb> u
> c:\users\morle\anaconda3\envs\spacepy\lib\re.py(173)match()
    171     """Try to apply the pattern at the start of the string, returning
    172     a Match object, or None if no match was found."""
--> 173     return _compile(pattern, flags).match(string)
    174
    175 def fullmatch(pattern, string, flags=0):

ipdb> string
'directory/99'
ipdb> pattern
'^directory\\99$'
ipdb> pattern = r'directory\\99$'
ipdb> _compile(pattern, flags).match(string)
ipdb> pattern = 'directory\\99$'
ipdb> _compile(pattern, flags).match(string)
*** re.error: invalid group reference 99 at position 10
ipdb> u
> c:\users\morle\anaconda3\envs\spacepy\lib\site-packages\spacepy\datamanager.py(214)match()
    212             raise(ValueError("where must be 'start', 'stop', or None, not {0}".
    213                              format(where)))
--> 214         return re.match('^' + pat + '$', string)
    215
    216     @staticmethod
```
Obviously the pattern is passed as a variable, so it can't be "converted" to raw, but it suggests that trying to handle path separators in a platform-independent way should be able to fix this.

**Comment by jtniehof** [comment]
RePath explicitly uses Unix path separators, since it's mean to be relevant to web addresses as well, and the idea is you can set up a description that can be handed back and forth across platforms without rewriting all the slash/backslash nonsense. So it's maybe not surprising it goes weird on Windows, where I certainly hadn't tested it before this. 

The error looks like a place where you might have already tried to change to local path separators? Not sure off the top of my head where the backslash would have come from otherwise.

**Comment by jtniehof** [comment]
I should be able to get this fixed later today. I just hate working in Windows; it's like using a glovebox.
