### ISSUE TITLE
spacepy.toolbox.update(QDomni=True) failing

### ISSUE THREAD

**Issue by ChrisSWDavis** [spacepy/spacepy#621]
When I try to update Qin-Denton/OMNI2 data in an attempt to get the data relevant for calculating McIlwain Lm values, spacepy hangs for a long time before failing due to connection issues:

i.e.
```
from spacepy import toolbox
toolbox.update(QDomni=True)
```

returns the following output:
```
Retrieving initial Qin-Denton file ...
Processing initial Qin-Denton file ...
Supplementing with latest Q-D daily files, this will take a while...
Finding Q-D daily files to download ...
Listing files ...0%Traceback (most recent call last):
  File "/usr/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 1418, in connect
    super().connect()
  File "/usr/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/spacepy/toolbox/__init__.py", line 1351, in update
    dailyomnidata = _get_qindenton_daily(cached=cached, startyear=startyear)
  File "/usr/local/lib/python3.8/dist-packages/spacepy/toolbox/__init__.py", line 832, in _get_qindenton_daily
    _crawl_yearly(qd_daily_url, r'QinDenton_\d{8}_hour.txt',
  File "/usr/local/lib/python3.8/dist-packages/spacepy/toolbox/__init__.py", line 753, in _crawl_yearly
    data = get_url(base_url)
  File "/usr/local/lib/python3.8/dist-packages/spacepy/toolbox/__init__.py", line 1134, in get_url
    r = urllib.request.urlopen(r)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>
```
The command hangs on
> Listing files...

 for several minutes in total. 

I suspect the issue is simply that https://rbsp-ect.newmexicoconsortium.org/data_pub/QinDenton/ is down, and I can't seem to reach the site in my web browser. Does anyone know of any workarounds or fixes that might solve this issue?

### Version of SpacePy
0.3.0

**Comment by drsteve** [comment]
Thanks Chris,
We don't have an ETA on the Van Allen Probes ECT SOC website coming back up right now, but https://github.com/spacepy/spacepy/discussions/616#discussioncomment-3003388 may be helpful.

We're still working on a short-term fix, but in the longer term we're working with NASA CCMC to transition that data production and service to them.
