### ISSUE TITLE
spacepy fails to build do to missing distutils.msvccompiler on Mac Big Sur

### ISSUE THREAD

**Issue by elwinter** [spacepy/spacepy#633]
I have been trying to install spacepy 0.3.0 on my Big Sur Mac. I tried the simplest possible installations using python 3.7, 3.8, and 3.9 environments , using instructions at https://spacepy.github.io/install_mac.html.

All resulted in the same error, as shown below:

```
conda create kaiju-3.8 python=3.8
conda activate kaiju-3.8
conda install gfortran_osx-64
conda install numpy scipy matplotlib h5py
pip install spacepy
```

For python 3.7, 3.8, 3.9 (using the analogous instructions above), the result was always the same:

```
      Traceback (most recent call last):
        File "/Users/winteel1/anaconda3/envs/kaiju-3.8/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/Users/winteel1/anaconda3/envs/kaiju-3.8/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/winteel1/anaconda3/envs/kaiju-3.8/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/private/var/folders/pl/hvfwp56s6ml6fwnq1mkcptdh0000gp/T/pip-build-env-xvca2wi0/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 412, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/private/var/folders/pl/hvfwp56s6ml6fwnq1mkcptdh0000gp/T/pip-build-env-xvca2wi0/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 397, in _build_with_temp_dir
          self.run_setup()
        File "/private/var/folders/pl/hvfwp56s6ml6fwnq1mkcptdh0000gp/T/pip-build-env-xvca2wi0/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 482, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/private/var/folders/pl/hvfwp56s6ml6fwnq1mkcptdh0000gp/T/pip-build-env-xvca2wi0/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 40, in <module>
        File "/private/var/folders/pl/hvfwp56s6ml6fwnq1mkcptdh0000gp/T/pip-build-env-xvca2wi0/overlay/lib/python3.8/site-packages/numpy/distutils/core.py", line 24, in <module>
          from numpy.distutils.command import config, config_compiler, \
        File "/private/var/folders/pl/hvfwp56s6ml6fwnq1mkcptdh0000gp/T/pip-build-env-xvca2wi0/overlay/lib/python3.8/site-packages/numpy/distutils/command/config.py", line 19, in <module>
          from numpy.distutils.mingw32ccompiler import generate_manifest
        File "/private/var/folders/pl/hvfwp56s6ml6fwnq1mkcptdh0000gp/T/pip-build-env-xvca2wi0/overlay/lib/python3.8/site-packages/numpy/distutils/mingw32ccompiler.py", line 28, in <module>
          from distutils.msvccompiler import get_build_version as get_build_msvc_version
      ModuleNotFoundError: No module named 'distutils.msvccompiler'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for spacepy
Failed to build spacepy
ERROR: Could not build wheels for spacepy, which is required to install pyproject.toml-based projects
```

The suggested dignostics:

```
import platform
import sys
import numpy
import scipy
import matplotlib

print(platform.platform())
print(sys.version_info)
print('numpy={0}'.format(numpy.__version__))
print('scipy={0}'.format(scipy.__version__))
print('matplotlib={0}'.format(matplotlib.__version__))
```
resulted in:

```
/Users/winteel1/anaconda3/envs/kaiju-3.8/lib/python3.8/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.1
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
macOS-10.16-x86_64-i386-64bit
sys.version_info(major=3, minor=8, micro=13, releaselevel='final', serial=0)
numpy=1.23.1
scipy=1.7.3
matplotlib=3.5.1
```

The spacepy installs were all done for 0.3.0, from PyPI.

As a sanity check, I made sure `gfortran` was in my PATH, and it is:

```
(kaiju-3.8) C02DT5CZMD6T-ML:Gamera-test winteel1$ which gfortran
/Users/winteel1/anaconda3/envs/kaiju-3.8/bin/gfortran
gfortran --version
GNU Fortran (GCC) 4.8.5
```

I suspect there is something subtly wrong with my environment, but I cannot for the life of me determine what it is, since I see the same issue with minimal environments with python 3.7, 3.8, and 3.9.

Is there something obvious I am missing?

Thanks in advance for any help.

Take care
Eric Winter
eric.winter@jhuapl.edu

**Comment by drsteve** [comment]
This recently hit quite a few packages...

It seems that `setuptools` recently introduced a breaking change (https://github.com/pypa/setuptools/issues/3532) and many projects haven't pinned the required version of `setuptools`. The short term fix is probably (and I'll test when I can) to roll back the version of `setuptools` you're using. Hopefully none of the packages force a `setuptools` update as part of their installation. Otherwise installing from source may be the best workaround. 

Other packages are also working on this, e.g.,  https://github.com/pyodide/pyodide/issues/2971, https://github.com/numpy/numpy/issues/22135, https://discourse.pymc.io/t/conda-install-error/10163, ...

I imagine we can fairly quickly pin the `setuptools` version, but I'm not sure how things will phase with our next release. I'm sure that @jtniehof has better insight into both the problems and solutions than I do.

**Comment by elwinter** [comment]
Thanks for the info folks. I actually encountered the `numpy.distutils` deprecation problem last week. The quick temporary workaround for that was dropping back to python 3.7 to confirm, and then going back to python 3.8 and adding `use_irbem=False` to some of the `Coords()` calls.

But then yesterday I encountered this damn `setuptools.msvccompiler` on my Mac. And then again today, on `cheyenne.ucar.edu`, using python 3.7, as described above.

As a test, I downgraded my `setuptools` to the previous available conda-available version (58.0.4), but the problem remains. I'll try to find a more recent older version on PyPI or conda-forge.

I'll post results here when I have them.

Take care
Eric

**Comment by elwinter** [comment]
FWIW, I tried rolling back `setuptools` as far as version 54, and the problem remains.

**Comment by xbonnin** [comment]
UPDATE:

I've run the two successive commands on a clean virtualenv and it works:

`pip install setuptools==54`
then
`pip install spacepy`

NOTE: Done on MacOs Big Sur with a Python 3.8.10 virtualenv using pip 22.2.2

**Comment by elwinter** [comment]
Well damn, it worked that time. I must have done something wrong yesterday when I was test-installing different versions. Thanks - this is a big help.

**Comment by Saransh-cpp** [comment]
FYI: This has been fixed in the new `setuptools` release - https://github.com/pypa/setuptools/compare/v65.0.1...main (reverts back the breaking change).
