### ISSUE TITLE
Error with Spacepy Version 0.5.0a0: Bats2d add_grid_plot function Error

### ISSUE THREAD

**Issue by rewoldt** [spacepy/spacepy#711]
I encountered an attribute error while attempting to use the add_grid_plot function from Bats2d to plot an AMR grid. This issue emerged following my update to the most recent version of Spacepy from the GitHub repository. This function worked in the previous version I had been using, which hadn't been updated for approximately six months.

### Minimal example to reproduce issue:

```
#!/usr/bin/env python

# Plotting utilities:
import matplotlib.pyplot as plt
import spacepy.plot as splot
from matplotlib import gridspec

# Top-level and model-specific Pybats modules:
from spacepy import pybats
from spacepy.pybats import bats, rim

gm_path = '/Users/rewoldt/dan-files/'

mhd_zslice = bats.Bats2d(gm_path+'z=0_mhd_2_e20150321-000000-000_20150321-040000-000.outs')
mhd_zslice.calc_ndens()
mhd_zslice.calc_b()
mhd_zslice.calc_j()

#for i in range(120, mhd_yslice.attrs['nframe'], 5):
for i in range(120, mhd_zslice.attrs['nframe']):
    mhd_zslice.switch_frame(i)
    fig, ax = mhd_zslice.add_grid_plot()
```

### Error message/Traceback:

```
Traceback (most recent call last):
  File "/Users/rewoldt/Library/Python/3.9/lib/python/site-packages/spacepy/pybats/bats.py", line 807, in qtree
    self._qtree = qo.QTree(points, blocksize=self.blocksize)
  File "/Users/rewoldt/Library/Python/3.9/lib/python/site-packages/spacepy/pybats/qotree.py", line 72, in __init__
    self._spawn_kids(grid)
  File "/Users/rewoldt/Library/Python/3.9/lib/python/site-packages/spacepy/pybats/qotree.py", line 196, in _spawn_kids
    self._spawn_kids(grid, k)
  File "/Users/rewoldt/Library/Python/3.9/lib/python/site-packages/spacepy/pybats/qotree.py", line 196, in _spawn_kids
    self._spawn_kids(grid, k)
  File "/Users/rewoldt/Library/Python/3.9/lib/python/site-packages/spacepy/pybats/qotree.py", line 196, in _spawn_kids
    self._spawn_kids(grid, k)
  [Previous line repeated 5 more times]
  File "/Users/rewoldt/Library/Python/3.9/lib/python/site-packages/spacepy/pybats/qotree.py", line 179, in _spawn_kids
    linspace(self[i].lim[0], self[i].lim[1], blksize+1),
UnboundLocalError: local variable 'blksize' referenced before assignment
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
File ~/Library/Python/3.9/lib/python/site-packages/spacepy/pybats/bats.py:807, in Bats2d.qtree(self)
    806     points = np.array([self[xdim], self[ydim]])
--> 807     self._qtree = qo.QTree(points, blocksize=self.blocksize)
    808 except Exception:

File ~/Library/Python/3.9/lib/python/site-packages/spacepy/pybats/qotree.py:72, in QTree.__init__(self, grid, blocksize)
     71 self.locs = lexsort((grid[0, :], grid[1, :]))
---> 72 self._spawn_kids(grid)
     73 self.nbranch = len(list(self.keys()))

File ~/Library/Python/3.9/lib/python/site-packages/spacepy/pybats/qotree.py:196, in QTree._spawn_kids(self, grid, i)
    195 self[k] = [x[j], x[j]+dx, y[j], y[j]+dx]
--> 196 self._spawn_kids(grid, k)

File ~/Library/Python/3.9/lib/python/site-packages/spacepy/pybats/qotree.py:196, in QTree._spawn_kids(self, grid, i)
    195 self[k] = [x[j], x[j]+dx, y[j], y[j]+dx]
--> 196 self._spawn_kids(grid, k)

    [... skipping similar frames: QTree._spawn_kids at line 196 (5 times)]

File ~/Library/Python/3.9/lib/python/site-packages/spacepy/pybats/qotree.py:196, in QTree._spawn_kids(self, grid, i)
    195 self[k] = [x[j], x[j]+dx, y[j], y[j]+dx]
--> 196 self._spawn_kids(grid, k)

File ~/Library/Python/3.9/lib/python/site-packages/spacepy/pybats/qotree.py:179, in QTree._spawn_kids(self, grid, i)
    177     self.dx_min = dx
    178 self[i].cells = meshgrid(
--> 179         linspace(self[i].lim[0], self[i].lim[1], blksize+1),
    180         linspace(self[i].lim[2], self[i].lim[3], blksize+1))
    181 self.nleafs += 1

UnboundLocalError: local variable 'blksize' referenced before assignment

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
Cell In [10], line 4
      2 for i in range(120, mhd_zslice.attrs['nframe']):
      3     mhd_zslice.switch_frame(i)
----> 4     fig, ax = mhd_zslice.add_grid_plot()

File ~/Library/Python/3.9/lib/python/site-packages/spacepy/pybats/bats.py:1638, in Bats2d.add_grid_plot(self, target, loc, do_label, do_fill, show_nums, show_borders, cmap, title)
   1635 ax.set_aspect('equal')
   1637 # Set plot range based on quadtree.
-> 1638 ax.set_xlim([self.qtree[1].lim[0], self.qtree[1].lim[1]])
   1639 ax.set_ylim([self.qtree[1].lim[2], self.qtree[1].lim[3]])
   1640 # Plot.

File ~/Library/Python/3.9/lib/python/site-packages/spacepy/pybats/bats.py:812, in Bats2d.qtree(self)
    810         print_exc()
    811         self._qtree = False
--> 812         self.find_block = lambda: False
    813 else:
    814     self._qtree = False

AttributeError: can't set attribute
```

### OS, Python version, and dependency version information:

```
macOS-13.4.1-arm64-arm-64bit
sys.version_info(major=3, minor=9, micro=16, releaselevel='final', serial=0)
numpy=1.23.4
scipy=1.9.1
matplotlib=3.6.0
```

### Version of SpacePy

Current version of spacepy: Version: 0.5.0a0
pulled from github: https://github.com/spacepy/spacepy

**Comment by jtniehof** [comment]
Thanks for the detailed report! I can't reproduce with the sample data I have, so it would help if you could put the output file somewhere I can grab it from.

@spacecataz is the expert here, so without reproduction I'm just taking a stab. But it looks like this was introduced in 4538eaebfa47557a97cba13c6613ed85e7cf9c8e of #697. I'm thinking the blksize calculation on 112 should probaby be done up around line 100 with the rest of the grid information so it's available in both the integer a case and not.

**Comment by jtniehof** [comment]
Since this is a regression we should probably treat it as a blocker for 0.5.
