### ISSUE TITLE
spacepy 0.6.0 does not build with setuptools 70.0

### ISSUE THREAD

**Issue by jtniehof** [spacepy/spacepy#746]
setuptools 70 changed the API such that spacepy 0.6.0 will not build. Prebuilt binary wheels will still install, so this should not affect most users. Anybody installing from source should either use setuptools 69 (or earlier) or build from git `main`.

This is fixed in #745 but I'm creating this issue to document the situation and workaround until the next release.

**Comment by johncoxon** [comment]
I'm getting the following behaviour when running `pip install spacepy`, is this issue the reason behind it? If so, can there be a 0.6.1 release that releases the bugfix in `main` into PyPI?

```
Collecting spacepy
  Using cached spacepy-0.6.0.tar.gz (7.7 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [66 lines of output]
      Ignoring numpy: markers 'python_version == "3.6"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.7" and (platform_system != "Darwin" or platform_machine != "arm64")' don't match your environment
      Ignoring numpy: markers 'python_version == "3.7" and platform_system == "Darwin" and platform_machine == "arm64"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.8" and (platform_system != "Darwin" or platform_machine != "arm64")' don't match your environment
      Ignoring numpy: markers 'python_version == "3.8" and platform_system == "Darwin" and platform_machine == "arm64"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.9" and (platform_system != "Darwin" or platform_machine != "arm64")' don't match your environment
      Ignoring numpy: markers 'python_version == "3.9" and platform_system == "Darwin" and platform_machine == "arm64"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.10"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.11"' don't match your environment
      Collecting setuptools
        Using cached setuptools-75.3.0-py3-none-any.whl.metadata (6.9 kB)
      Collecting wheel
        Using cached wheel-0.44.0-py3-none-any.whl.metadata (2.3 kB)
      Collecting numpy~=1.24.0
        Using cached numpy-1.24.4.tar.gz (10.9 MB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'error'
        error: subprocess-exited-with-error
      
        × Getting requirements to build wheel did not run successfully.
        │ exit code: 1
        ╰─> [32 lines of output]
            Traceback (most recent call last):
              File "/Users/swvl7local/.micromamba/envs/work/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
                main()
                ~~~~^^
              File "/Users/swvl7local/.micromamba/envs/work/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
                json_out['return_val'] = hook(**hook_input['kwargs'])
                                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
              File "/Users/swvl7local/.micromamba/envs/work/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
                backend = _build_backend()
              File "/Users/swvl7local/.micromamba/envs/work/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
                obj = import_module(mod_path)
              File "/Users/swvl7local/.micromamba/envs/work/lib/python3.13/importlib/__init__.py", line 88, in import_module
                return _bootstrap._gcd_import(name[level:], package, level)
                       ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
              File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
              File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
              File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
              File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
              File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
              File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
              File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
              File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
              File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
              File "/private/var/folders/xd/zqbphtc51rv1h5nqgf0lgws40000gr/T/pip-build-env-itacb0kh/overlay/lib/python3.13/site-packages/setuptools/__init__.py", line 16, in <module>
                import setuptools.version
              File "/private/var/folders/xd/zqbphtc51rv1h5nqgf0lgws40000gr/T/pip-build-env-itacb0kh/overlay/lib/python3.13/site-packages/setuptools/version.py", line 1, in <module>
                import pkg_resources
              File "/private/var/folders/xd/zqbphtc51rv1h5nqgf0lgws40000gr/T/pip-build-env-itacb0kh/overlay/lib/python3.13/site-packages/pkg_resources/__init__.py", line 2172, in <module>
                register_finder(pkgutil.ImpImporter, find_on_path)
                                ^^^^^^^^^^^^^^^^^^^
            AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: subprocess-exited-with-error
      
      × Getting requirements to build wheel did not run successfully.
      │ exit code: 1
      ╰─> See above for output.
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by jtniehof** [comment]
@johncoxon was building against numpy 1.24 so that's probably not it here. Regardless, setuptools 75 is known not to work, and #766 has relevant 2.0 fixes.

Can you try the release candidate per directions in #794 and let me know how it goes? Both using the wheel and building from source would be great to help me smoke out any problems, but whatever gets you to what you need.

**Comment by swkre** [comment]
Version 0.7.0 installs without issue. Not sure what my previous issue was, but it works now. Thank you for all the work you do supporting this!!

**Comment by jtniehof** [comment]
Yeah, there are enough things that got patched up that it's hard to tell _what_ the fix was, just so long as it's fixed!

**Comment by johncoxon** [comment]
Running `pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ "spacepy==0.7.0rc1"` worked for me, as did just cloning the main branch of this repo and pip installing that.
